### ISSUE TITLE
Ebay link is no longer working for Bluetooth adapter

### ISSUE THREAD

**Issue by tomicooler** [uholeschak/ediabaslib#10]
Hello,

I have a BMW E46 330i (2004), I would like to use the android application, but my OBDLink LX, and ELM327 clone device is not working.

There is a link for bluetooth adapters on this documentation page, but it's a dead link:
 https://github.com/uholeschak/ediabaslib/blob/master/docs/Replacement_firmware_for_ELM327.md

Can you provide a proper ebay link to get one of these adapters? Thanks.

**Comment by uholeschak** [comment]
The link is correct, because all adapters are sold at the moment.

**Comment by uholeschak** [comment]
The link is now updated:
https://www.ebay.de/itm/253421755051
