### ISSUE TITLE
K+DCAN cable update

### ISSUE THREAD

**Issue by SantCineva** [uholeschak/ediabaslib#103]
I've come across this tutorial ( http://blog.obdii365.com/2021/07/09/update-inpa-kdcan-cable-with-enhanced-firmware/ ) and I wanted to know if it would work  on a normal K+DCAN cable like the ones in the tutorial without modifiing anything else.
Should I just update the flash and fuses and expect everything to work?
I'm mostly using DIS software and INPA.

**Comment by uholeschak** [comment]
I think you should ask this the creator of the tutorial.

**Comment by SantCineva** [comment]
What do you mean? Can't you clarify this?

**Comment by uholeschak** [comment]
This tutorial is not from me, so I can't tell you anything about it.
http://blog.obdii365.com/2021/07/09/update-inpa-kdcan-cable-with-enhanced-firmware/

**Comment by SantCineva** [comment]
I tested it myself on a green PCB, K+DCAN adapter, and it works .
I thought it might be a good idea to leave some feedback here. I've seen a lot of people having the same question on a fiew forums.
Is there any chance I could get the source code of the file "Combined.hex"? Or at least some documentation on it?

**Comment by uholeschak** [comment]
Its all open source:
https://github.com/uholeschak/ediabaslib/tree/master/EdiabasLib/CanAdapter
