### ISSUE TITLE
Cannot connect to z3 ews

### ISSUE THREAD

**Issue by dimiras** [uholeschak/ediabaslib#107]
Hi,
Im looking for some help.
I'm trying to recode the OBC from my Pre-Facelift z3 but I am not able to connect to it using my Ebay Inpa Cable.
Before adding this library to my ediabas setup I was able to connect to my ews using INPA/NCS Expert and read it ( was not able to connect to any of the other ecus) but now with your library in place I am not able to connect to anything, ews included.

Is there any tutorial explaining how to use this library? do I need to modify my cable? do I need to install some custom firmware to make my cable work?

Thanks

**Comment by uholeschak** [comment]
Basically if would think this should work with DS2 and BMW-FAST protocols
For other I would recommend the DEEP OBD Adapter.
Doc for config file:
https://github.com/uholeschak/ediabaslib/blob/master/docs/EdiabasLib.config_file.md
