### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by neuronet77** [uholeschak/ediabaslib#108]
Hello Ulrich,

Thanks a lot for your awesome work on this so awesome project.

I'm trying to get it compiled on Win 10 / VS2019 Community

`git clone https://github.com/uholeschak/ediabaslib.git`
`cd ediabaslib`
`git submodule init`
`git submodule update`

Then changing the JDK location the open-jdp provided by MS:

`C:\Program Files\Microsoft\jdk-17.0.1.12-hotspot`

Even reinstalled all NuGet packages...

Compiler Error:

`C:\Users\happycoding\Desktop\ediabaslib\BmwDeepObd\ExpansionDownloaderActivity.cs(20,15,20,21): error CS0234: The type or 
6>namespace name 'Google' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?)`

What am I missing?

**Comment by uholeschak** [comment]
At least you need JDK11 for the current state.
Simply install Xamarin correctly, there are 1000 traps ...
