### ISSUE TITLE
Deep ODB installation - endless loops in "extracting files" as soon as screen lock was activated

### ISSUE THREAD

**Issue by mi-hol** [uholeschak/ediabaslib#110]
Android phones have usually a time set to lock automatically.
When Deep ODB Version 1.3.58 "extract files" is running at the time screen lock gets activated, the process seems to stop.
At least when phone is unlocked, Deep ODB displays the "Question" dialog and asks for yes/no confirmation to extract 2.3GB ECU files again.
This results in an endless loop and installation never finishes.
Installation should correctly handle "device lock" and "device unlock" events and resume gracefully.

**Comment by uholeschak** [comment]
I expect the app will terminate. The only way would be preventing the lock.

**Comment by mi-hol** [comment]
> preventing the lock.

correct, this approach is used by video players, navigation apps.
Maybe the source code of vlc for android contains the solution.

**Comment by uholeschak** [comment]
At the moment I have only kept the CPU active, change it to display dim. Have to test it when I have time.

**Comment by mi-hol** [comment]
In case a .apk file is downloadable, I'd be happy to test

**Comment by uholeschak** [comment]
I have uploaded Version 1.3.60
https://play.google.com/apps/testing/de.holeschak.bmw_deep_obd

**Comment by mi-hol** [comment]
Great news, the change fixed the issue!
Thanks you so much.

**Comment by uholeschak** [comment]
Thanks for the feedback.
