### ISSUE TITLE
OBD Modes support with FTDI cable possible?

### ISSUE THREAD

**Issue by why-1998** [uholeschak/ediabaslib#115]
Hi!
Is it possible to send "standard" OBD requests via FTDI cable using EdiabasLib to get i.e. Mode 6 data like misfire counters or alike?
Thanks!

**Comment by uholeschak** [comment]
What do you mean with standard request? With TMODE.prg you are at least able to define custom telegrams.
Of course you could also simply open a COM port and send directly.
