### ISSUE TITLE
IBM / Yandex translator getting your credit card ...

### ISSUE THREAD

**Issue by ulysse31** [uholeschak/ediabaslib#116]
Hello,

IBM translate is getting pay as you go for particulars (need to enter credit card now), and Yandex, says that you'll get a "free 75$ bonus for translation" ... but only if you enter your credit card informations ...
Is it possible to implement something free for translations ? or use google translate API (which is linked to our google account, better integration and payement information if needed already present).

Thanks a lot,

**Comment by uholeschak** [comment]
Do you have to pay or this only for information?

**Comment by uholeschak** [comment]
At the moment I see no limitation. The light account is still free.
