### ISSUE TITLE
Can not re-flash with elm327 firmware

### ISSUE THREAD

**Issue by GyurkanM** [uholeschak/ediabaslib#117]
After the last beta update or the previous one function to re-flash with elm327 through the deebobd is not working. Adapter is flashed with yc1021 firm and previously have changed between elm327 and ediabaslib many times.

**Comment by uholeschak** [comment]
Basically nothing has changed here. What exactly is the problem? Which update exactly cause the problem?

**Comment by GyurkanM** [comment]
I should try by reainstalling the app maybe, but also I changed the phone from lenovo p2 to galaxy s21, maybe this is the issue, will check with the old phone, also with the regular release, so I can pinpoint the exact problem.

**Comment by uholeschak** [comment]
I am also using a Galaxy S21, maybe I could check it again ...

**Comment by GyurkanM** [comment]
The issue resolved after several times re-pairing the adapter.

**Comment by uholeschak** [comment]
Thanks for the info, so probably this was a connection problem.
