### ISSUE TITLE
Can't find my start to flash the BK3231 chip

### ISSUE THREAD

**Issue by kareemtawab** [uholeschak/ediabaslib#120]
Hello,

Thanks for having time to build this awesome project. However, I can't start using my adapter with the replacement v1.5 firmware. I have a Bluetooth adapter with an MCP2515 and a BK3231Q as the controller and bluetooth combo. I'm not sure of the most suitable binary file that is suitable. I also I don't know where to connect a programmer and the type of programmer used. Pictures of the adapter are provided.

![1](https://user-images.githubusercontent.com/24245215/167258078-18e70822-d8e9-4411-9f5a-2b5d3ffcb676.jpeg)
![2](https://user-images.githubusercontent.com/24245215/167258086-6fef78ba-f5ce-4555-a7bc-403c490e4f19.jpeg)

Any help is appreciated.

**Comment by uholeschak** [comment]
Sorry the fimrware is only for PIC processors.
