### ISSUE TITLE
Can it support running on linux ?

### ISSUE THREAD

**Issue by chaooe** [uholeschak/ediabaslib#123]

**Comment by uholeschak** [comment]
Basically Android is a linux core. You could use an Android emulator.

**Comment by uholeschak** [comment]
If I see it correctly the platform is using and android derivative.

**Comment by harryberlin** [comment]
It's Debian OS.

**Comment by uholeschak** [comment]
Ok, he is only using the Library dll. This is what I have mentioned before. Use it with mono, but you have to create your own application.
