### ISSUE TITLE
Reduce data volume used for each application update (i.e avoid ECU data download)

### ISSUE THREAD

**Issue by mi-hol** [uholeschak/ediabaslib#125]
With the frequent updates of application, each time a new version is released users are required to download all supporting data (currently 2.3GB).
Unfortunately the download is only requested at the time when Deep ODB is desperately needed for troubleshooting a car issue!
According to "Murphy's law" this will happen when no adequate remote connection bandwidth is available.
Usability is greatly impacted in a negative way by current download approach.

Could this be improved?

Possible improvement approaches could be (in order of envisaged coding effort):

1. add a check if supporting data changed before download is triggered
2. offer to run application with outdated data as an emergency exception
3. add a daily background task to check for data download requirements and a setting for automatic or manual download

**Comment by uholeschak** [comment]
I expect you don't mean download of data but extraction of data.
In the last beta updates of course there was an update of the .obb file, but not in the release.
If the .obb files changes, extraction of data is required.
If this is a problem, use the release.
If extraction of data if required without app update, you have a problem with lost application data on your device.

**Comment by mi-hol** [comment]
Hallo Ulrich,

vorgestern wollte ich bei einem BMW Z4 (E85) den Fehlerspeicher auslesen, jedoch gab es wohl einen Kommunikationsfehler zwischen dem von dir gekauften OBD Adapter und der neuesten DeepOBD Version auf dem Handy.
Es kam ein Dialog der anbot den Fehler hochzuladen, da ich aber zu dem Zeitpunkt keine Internetverbindung hatte, gab das auch einen Fehler.

Im Log-Verzeichnis ist davon nichts zu finden.

Deshalb die Frage, könnten solche Fehlerprotokolle auf dem Gerät lokal gespeichert werden und später hochgeladen werden?

Viele Grüße

Michael HolzerMessage ID: ***@***.***>

**Comment by uholeschak** [comment]
Der letzte Trace ifh.trc das Hauptfensters befindet sich in Log, sofern man nichts mehr dazwischen macht.
Sie können ja auch das Fenster offen halten und sich eine Internetverbindung suchen und dann senden.

**Comment by mi-hol** [comment]
Leider sind diese Vorschläge nicht praktikabel, da zum Zeitpunkt des Tool-Problems das Problem des Autos die Priorität des Benutzer ist und das Tool DeepOBD den Ablauf einer technischen Fehlerdiagnose nicht noch weiter erschweren sollte.

Oder wie würden Sie da am Straßenrand im Nirgendwo bei solch einem Problem vorgehen?
 

Gesendet: Freitag, 02. September 2022 um 16:16 Uhr
Von: "Ulrich Holeschak" ***@***.***>
An: "uholeschak/ediabaslib" ***@***.***>
Cc: "mi-hol" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [uholeschak/ediabaslib] Reduce data volume used for each application update (i.e avoid ECU data download) (Issue #125)


 

Der letzte Trace ifh.trc das Hauptfensters befindet sich in Log, sofern man nichts mehr dazwischen macht.
Sie können ja auch das Fenster offen halten und sich eine Internetverbindung suchen und dann senden.

**Comment by uholeschak** [comment]
Einfach kein Trace senden ...

**Comment by mi-hol** [comment]
Schlechten Tag gehabt?
Die Antwort ist ja wirklich hilfreich :(
Kann ich den ODB Plug zurückgeben, der Erfolg damit geht nämlich gegen 0

 
 

Gesendet: Freitag, 02. September 2022 um 16:46 Uhr
Von: "Ulrich Holeschak" ***@***.***>
An: "uholeschak/ediabaslib" ***@***.***>
Cc: "mi-hol" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [uholeschak/ediabaslib] Reduce data volume used for each application update (i.e avoid ECU data download) (Issue #125)


 

Einfach kein Trace senden ...

**Comment by uholeschak** [comment]
Sorry ja das stimmt, der Tag war nicht besonders toll.
Sagen wir mal so, die Traces schaue ich mir nur an, wenn es einen Grund dafür gibt, also normalerweise nicht.
Von daher können sie sich das senden sparen, es sein denn sie sagen mir explizit, schauen sich sich das mal an.

**Comment by uholeschak** [comment]
Wobei mir jetzt einfällt, es gibt sogar da einen Funktion.
Wenn das Senden fehlschlägt, gibt es im Menü einen Eintrag:
Trace Datei erneut senden
Damit kann man es nochmals versuchen.

**Comment by uholeschak** [comment]
Aber wie gesagt, anschauen tue ich mir das nur, wenn sie das explizit sagen, zusammen mit AppID.
Da kommen man Tag so viele Dateien, da könnte man eine ganze Mannschaft mit beschäftigen.

**Comment by uholeschak** [comment]
Aber was tatsächlich fehlt, ist ein Hinweis in der Fehlermeldung auf die Sendefunktion.

**Comment by mi-hol** [comment]
ok. Mein Verbesserungsvorschlag wäre die Funktion "send trace file" in https://github.com/uholeschak/ediabaslib/blob/master/docs/Deep_OBD_for_BMW_and_VAG.md#log-and-trace-files-location zu ergänzen und dort auch zu erwähnen wie man die  AppID raus bekommt. Daran bin ich gerade gescheitert

 

Wenn da so viel ankommt, ist das mMn ein starker Hinweis, dass mit der App etwas sehr faul ist.


"Telemetrie" die nicht ausgewertet wird ist nicht besonders sinnvoll, vielleicht sollte das ein Schwerpunkt für die Entwicklung werden.

 

 

Gesendet: Freitag, 02. September 2022 um 19:57 Uhr
Von: "Ulrich Holeschak" ***@***.***>
An: "uholeschak/ediabaslib" ***@***.***>
Cc: "mi-hol" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [uholeschak/ediabaslib] Reduce data volume used for each application update (i.e avoid ECU data download) (Issue #125)


 

Aber wie gesagt, anschauen tue ich mir das nur, wenn sie das explizit sagen, zusammen mit AppID.
Da kommen man Tag so viele Dateien, da könnte man eine ganze Mannschaft mit beschäftigen.

**Comment by uholeschak** [comment]
Danke da hat es auch noch gefehlt.
Vermutlich wäre es der bessere Weg die Meldung mit dem Tarce nicht mehr bei jedem Husten anzuzeigen, sondern nur noch bei schwerem Fieber.

**Comment by uholeschak** [comment]
Gute Idee, ich habe jetzt eine Schwelle von 10 eingebaut, dass sollte das Senden etwas eindämmen und wirkt gleich stabiler.

**Comment by uholeschak** [comment]
Das Problem ist, dass bei 99% der Tarces entweder die Verbindung schlecht ist, ein falsche Adapter verwendet wurde oder etwas am Fahrzeug defekt ist. Das ist absolut uninteressant. Die Schwierigkeit besteht halt darin, das schon auf der App Seite zu erkennen was das unterlagerte Problem ist und die Traces erst gar nicht mehr zu senden.

**Comment by mi-hol** [comment]
ich finde die AppId leider nicht, denn der laut Doc vorhanden Menüpunkt "* _App info_: Displays the app version and unique id." wird nicht angezeigt. Könntest Du das bitte prüfen

 
 

Gesendet: Freitag, 02. September 2022 um 23:42 Uhr
Von: "Ulrich Holeschak" ***@***.***>
An: "uholeschak/ediabaslib" ***@***.***>
Cc: "mi-hol" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [uholeschak/ediabaslib] Reduce data volume used for each application update (i.e avoid ECU data download) (Issue #125)


 

Das Problem ist, dass bei 99% der Tarces entweder die Verbindung schlecht ist, ein falsche Adapter verwendet wurde oder etwas am Fahrzeug defekt ist. Das ist absolut uninteressant. Die Schwierigkeit besteht halt darin, das schon auf der App Seite zu erkennen was das unterlagerte Problem ist und die Traces erst gar nicht mehr zu senden.

**Comment by uholeschak** [comment]
Ich sehe dort:
Deep OBD ...
Version: XXX
ID: YYYY
Es ist das YYYY

**Comment by mi-hol** [comment]
Anbei die Screenshots wie es bei mir aussieht.

Was mache ich jetzt?

 
 

Gesendet: Samstag, 03. September 2022 um 20:56 Uhr
Von: "Ulrich Holeschak" ***@***.***>
An: "uholeschak/ediabaslib" ***@***.***>
Cc: "mi-hol" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [uholeschak/ediabaslib] Reduce data volume used for each application update (i.e avoid ECU data download) (Issue #125)


 

Ich sehe dort:
Deep OBD ...
Version: XXX
ID: YYYY
Es ist das YYYY

**Comment by uholeschak** [comment]
Leider fehlt der Screenshot.

**Comment by uholeschak** [comment]
Zukünftig kommt die Meldung zum Trace senden nur, wenn min 3 Fehler aufgetreten sind und es überhaupt eine Antwort gab.
Kleine Störungen und fehlende Fahrzeugverbindung werden also ignoriert.

**Comment by mi-hol** [comment]
Ja, bei Fieber und wiederholtem Husten, denn dann ist auch was faul.

 

Ingesammt scheint es, wir haben da heute eine wirkliche Verbesserung der Usability geschafft.


 

Nur frage ich mich was passiert wäre, wenn ich nicht so professionell geantwortet hätte?

 

Gesendet: Freitag, 02. September 2022 um 21:05 Uhr
Von: "Ulrich Holeschak" ***@***.***>
An: "uholeschak/ediabaslib" ***@***.***>
Cc: "mi-hol" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [uholeschak/ediabaslib] Reduce data volume used for each application update (i.e avoid ECU data download) (Issue #125)


 

Danke da hat es auch noch gefehlt.
Vermutlich wäre es der bessere Weg die Meldung mit dem Tarce nicht mehr bei jedem Husten anzuzeigen, sondern nur noch bei schwerem Fieber.
