### ISSUE TITLE
PIC18F26K80 supported?

### ISSUE THREAD

**Issue by jvrodrisan** [uholeschak/ediabaslib#129]
Hi, I hope you are all good.

One of my OBD adapters include PIC18F26K80 instead of the PIC18F25K80 which is found in the doc. I have seen that the only difference is the memory (32kb vs 64kb). I have not yet tested it as I don't have the pickit3 programmer still. Is there any chance this PIC is supported by filling the 32kb of difference with zeroes?
Thanks

**Comment by uholeschak** [comment]
I already programmed these with the current image, is working fine.
