### ISSUE TITLE
Cannot set up the app

### ISSUE THREAD

**Issue by Bmwe39528** [uholeschak/ediabaslib#130]
I tried installing the app multiple times, tried beta app as well. When the app warns me that it will extract 2.4GB if files, I click "ok" and the whole process only takes two minutes. I don't know how it's possible to download 2.4GB data this fast, or if it doesn't download for some reason.
I cannot find the downloaded 2.4GB data.

I tried following the instructions on the screenshot from https://xtrons.ibus-app.de/index.php?title=DeepOBD_-_Adapter_und_App_einrichten#Zusammenfassung_und_Download but cannot find this folder anywhere
Android/data/de.holeschak.bmw_deep_obd/files

I will include some pictures and the instructions I follow. I'm not sure what I'm doing wrong?
![Screenshot_20221003-103446_Google Play Store](https://user-images.githubusercontent.com/114942085/193634297-b8d3c537-8e69-4f1a-a6da-7ebaa35f6ad5.jpg)
![Screenshot_20221003-103504_Google Play Store](https://user-images.githubusercontent.com/114942085/193634299-0b526b80-ea3c-4644-bba8-bd45fd980fa8.jpg)
![Screenshot_20221003-104008_Permission controller](https://user-images.githubusercontent.com/114942085/193634302-092f85e3-926b-4305-9466-5958efdfeea6.jpg)
![Screenshot_20221003-104021_Deep OBD](https://user-images.githubusercontent.com/114942085/193634305-8054d290-e46c-4b40-be24-b2a652ce39b5.jpg)
![Screenshot_20221003-104030_Deep OBD](https://user-images.githubusercontent.com/114942085/193634307-b8298463-39dd-416b-b9c3-a15a3143099c.jpg)
![Screenshot_20221003-104039_Deep OBD](https://user-images.githubusercontent.com/114942085/193634309-78bd019d-6c53-47fb-8b37-9ffab55f9831.jpg)
![Screenshot_20221003-104052_Deep OBD](https://user-images.githubusercontent.com/114942085/193634311-d24eddf6-2292-4885-8512-4a34e614014c.jpg)
![Screenshot_20221003-104126_Deep OBD](https://user-images.githubusercontent.com/114942085/193634312-fe02bd57-b892-4481-bfd4-1eaf56991c36.jpg)
![Screenshot_20221003-104135_Deep OBD](https://user-images.githubusercontent.com/114942085/193634317-4a6d7bd8-e4c8-4e38-8d14-0cb8d3994f28.jpg)
![Screenshot_20221003-104150_Deep OBD](https://user-images.githubusercontent.com/114942085/193634321-b78c51d4-93b5-44b2-8762-c77ade8dc2d3.jpg)
![Screenshot_20221003-104244_Deep OBD](https://user-images.githubusercontent.com/114942085/193634325-a7145040-3ea5-4863-bd02-2cd3f2f880ce.jpg)
![Screenshot_20221003_104559](https://user-images.githubusercontent.com/114942085/193634328-1e1c46bb-4b43-4285-8901-e50e16d01e7e.jpg)
![Screenshot_20221003_104956](https://user-images.githubusercontent.com/114942085/193634330-432b24ed-da4b-459e-9a66-c678ad5481ca.jpg)
![Screenshot_20221003-105017_My Files](https://user-images.githubusercontent.com/114942085/193634333-62e24c11-1bd2-4129-aa52-5fee0db349f2.jpg)
![Screenshot_20221003_105037](https://user-images.githubusercontent.com/114942085/193634335-8ebf53ad-f0a5-4043-9832-2b05b6fcce09.jpg)

**Comment by uholeschak** [comment]
If you don't have direct access to the app folder you have to use the "File management" options of the global settings to copy the external directory to the app:
https://github.com/uholeschak/ediabaslib/blob/master/docs/GlobalSettings.md

**Comment by uholeschak** [comment]
Officially it's recommended to use the configuration generator and not external files.
If there are problems with external files contact the supplier of these files.
