### ISSUE TITLE
Error: Reading VAG files failed - how to fix?

### ISSUE THREAD

**Issue by mi-hol** [uholeschak/ediabaslib#131]
After update to Version: 1.3.102  "Error: Reading VAG files failed"  is displayed
How can I fix it?

**Comment by uholeschak** [comment]
Is this the Release or the beta version of the app, but this should make no difference.
Either your ecu files are corrupted or there is not enough free memory for the database files.

**Comment by mi-hol** [comment]
is "Fixed ecu dir size calulation" a result of this issue?

**Comment by uholeschak** [comment]
You could try the beta, maybe you could see an exception message:
https://play.google.com/store/apps/details?id=de.holeschak.bmw_deep_obd

**Comment by mi-hol** [comment]
> I would recommend to use a different phone that is faster and has more memory.

competing OBD scanners work well on this phone, this should be an incentive to improve DeepOBD in this regard!

**Comment by mi-hol** [comment]
> I print now the exception text if an exception occurs.

good to read, this should always be the default behavior of good software

**Comment by uholeschak** [comment]
Sorry this is technically impossible.
When starting the app the first time, you have explicitly accepted that your phone is fast enough.

**Comment by uholeschak** [comment]
Then the exception is in a deeper layer. I will try to extract more messages.
Have you uninstalled all protection software, like anti virus scanners? They often block file access.

**Comment by uholeschak** [comment]
Good!

**Comment by uholeschak** [comment]
Have you tried to reextract the ECU files in VAG mode from the main menu?

**Comment by uholeschak** [comment]
How large is the delay between start of reading VAG files and the error message?

**Comment by mi-hol** [comment]
> When starting the app the first time, you have explicitly accepted that your phone is fast enough.

I'd suggest to move this topic to a new issue because in its current form the question can't be answered correctly by a user.
To be answered in a reliable way a reference to an objective measurement is required.
The question is therefore:
- what is/are this/these objective measurement(s)? 
**and** 
- can it be calculating during installation?

**Comment by mi-hol** [comment]
> Have you tried to reextract the ECU files in VAG mode from the main menu?

yes, this completed successfully



> How large is the delay between start of reading VAG files and the error message?

between "generate config" and error, first delay is 2-3 seconds, then if error is confirmed with "ok" and pressing "generate config" again, error shows instantly

**Comment by uholeschak** [comment]
Perhaps I misunderstand something here. Could you send a video to ulrich@holeschak.de?

**Comment by mi-hol** [comment]
> Could you send a video

would be a 3 second video with:
1.) start app
2.) see screen "no valid configuration", press "Generate"
3.) get error "Error: Reading VAG files failed"

Would it be possible to start app so it creates a trace (i.e. via a parameter)?

![Screenshot_20221015-102518](https://user-images.githubusercontent.com/22799428/195977827-e5d58089-948e-41bf-9a10-ba9d1e9660de.png)
![Screenshot_20221015-102553](https://user-images.githubusercontent.com/22799428/195977828-b156df29-8cb1-463f-a135-cde0ba700738.png)

**Comment by uholeschak** [comment]
Thanks, interesting would be the timing.
I could log something to Android LogCat, but there could be 1000 locations for the problem.
What you could do is to check LogCat anyway, maybe Android tells you something ...

**Comment by mi-hol** [comment]
I was able to solve this issue.
Apparently a ZIP file was corrupted, unfortunately I didn't capture the message.
After downloading und extracting VAG files again, it works now.
Still its weird that "verify files step" on first extract did NOT report any errors.
I'd suggest to add a test case with a corrupted zip archive

**Comment by uholeschak** [comment]
This is only a fast check, that compares size and if the file is present.
A deep check with CRC requires too much time. After extraction a deep check is performed,
If the file system is corrupted afterwards will not be detected.

**Comment by mi-hol** [comment]
> After extraction a deep check is performed,

I was referring to exactly this check.
Why does it not detect a corruption is the unsolved mystery
