### ISSUE TITLE
inpa D-CAN/K-line protocol and firmware

### ISSUE THREAD

**Issue by gauix4** [uholeschak/ediabaslib#132]
Hello
After several weeks of research I can not find the following information
which protocol uses INPA on a mini R50/53 because it is much faster than ISO 9141
I am also looking for the open source firmware of the D-CAN/K-Line cable because I find .bin which is absolutely not open source

I also tried to find threads or forums there is nothing at all
I'm looking to get myself a dashboard so no pc in the car but an ESP32
a computer has no place in a car that's why I'm looking to do everything on a microcontroller with a screen to view data only there is no information on the internet on k-line communication on mini or BMW
so i can't start any projects until i know what communication it uses moreover there is no open source firmware findable for inpa usb converter every time it's binary files so it's not Open Source I don't know why people call it open source!

I am therefore sending you this message hoping that you have answers to these questions your project is beautiful but for my part they use a computer which I do not want there are already at least the IDs that I can recover in your code this who is already good
thank you very much !

**Comment by uholeschak** [comment]
Sorry I have no experiences with Mini.

**Comment by gauix4** [comment]
> Désolé, je n'ai aucune expérience avec Mini.

there is not only mini all the vehicles which are on INPA use the same protocol I do not find which protocol it uses
you have encoded the IDs so you must have an idea of what protocol it is to have them encoded
```cpp
private static string Type104Convert(UdsReader udsReader, byte[] data)
        {
            if (data.Length < 6 + 1)
            {
                return string.Empty;
            }

            byte maskData = data[0];
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < 3; i++)
            {
                StringBuilder sbValue = new StringBuilder();
                bool bData1 = (maskData & (1 << i)) != 0;
                bool bData2 = (maskData & (1 << (i + 3))) != 0;
                if (bData1 || bData2)
                {
                    sbValue.Append("IAT ");
                    if (bData1)
                    {
                        sbValue.Append($"1{i + 1}");
                    }
                    if (bData2)
                    {
                        if (bData1)
                        {
                            sbValue.Append("/");
                        }
                        sbValue.Append($"2{i + 1}");
                    }
                    sbValue.Append(": ");

                    if (bData1)
                    {
                        byte value = data[i + 1];
                        double displayValue = value - 40.0;
                        sbValue.Append($"{displayValue:0.}");
                    }
                    if (bData2)
                    {
                        byte value = data[i + 3 + 1];
                        double displayValue = value - 40.0;
                        if (bData1)
                        {
                            sbValue.Append("/");
                        }
                        sbValue.Append($"{displayValue:0.}");
                    }
                    sbValue.Append(" ");
                    sbValue.Append(GetUnitMapText(udsReader, 3) ?? string.Empty); // °C

                    if (sb.Length > 0)
                    {
                        sb.Append("; ");
                    }
                    sb.Append(sbValue);
                }
            }

            return sb.ToString();
        }
```

**Comment by uholeschak** [comment]
This function is for VAG sorry.

**Comment by uholeschak** [comment]
I would recommend to use ISTA-D and log the communication.

**Comment by gauix4** [comment]
I'll look into that thanks but I think it still uses ISO 9141 for diagnostics anyway

**Comment by uholeschak** [comment]
The protocol depends for the ecu file used, so you have to check the corresponding ecu file.
Ediabas only gets the parameters.

**Comment by gauix4** [comment]
Where is this file stored ? Please :) 
I can't find when the files each time I come across the VAG

My ECU is EMS2K
Siemens C167

**Comment by uholeschak** [comment]
What exactly do you wan to know?
Simply check the apps ecu directory where the files are extracted.

**Comment by gauix4** [comment]
I'm looking for the UDS to decode this
its data ans generated and retrieved by ediabas so it is probably in the files you have attached but I can't find them there are too many files I tested with the search function it only gives me VAG

![325523481_1179383792745112_1068570767465367027_n](https://user-images.githubusercontent.com/23041016/217953045-4cad30fd-562f-4f65-b154-fd11c6a9573f.png)

**Comment by uholeschak** [comment]
I think analyzing the ecu file will not really help you, its too complicated.
Better to simply reverse engineer form the logged data you have.

**Comment by gauix4** [comment]
ediabas the deciphers
I will therefore have to find my answer in ediabase normally

It's to code all this on an ESP32
I can already talk to the ECU and I understand a lot of the data

**Comment by uholeschak** [comment]
I expect that I also simply don't know the answer, the info probably in hidden in manufacturer specific files.

**Comment by gauix4** [comment]
EdiabasLib/UdsFileReader/UdsReader.cs
I'm not sure this and that for wv if ?

**Comment by uholeschak** [comment]
Yes this is for VAG. But the manufacturer specific data is not included in the repo and is encrypted to prevent extraction.
Nobody will help you to extract this data.
