### ISSUE TITLE
Improve zip file extracting

### ISSUE THREAD

**Issue by mi-hol** [uholeschak/ediabaslib#133]
![Screenshot_20221015-120853](https://user-images.githubusercontent.com/22799428/195994000-be1f74d3-f42e-4baf-8c40-643988caca06.png)

The current logic should be improved to:

1. check available free space on configured storage device
2. read "expanded" file size from zip archive
3. compare the 2 sizes and only if not enough free is available
4. display error with the exact amount of space missing, abort extraction before free space is exhausted!
5. revise current "unspecific error in above image" and provide the unique error code from library used to extract archive to file system, file names and other relevant information requiring for solving issue by user

**Comment by uholeschak** [comment]
Basically in the current beta version there is check for the free space that should be correct.
This message is only  fallback if something unknown happens.

**Comment by mi-hol** [comment]
> This message is only fallback if something unknown happens.
> I would expect that there is a problem in the file system layer.

then text of message should reflect that

**Comment by uholeschak** [comment]
I could remove the sentence: "Is there no space left on the device?"
The exception message is below in your screenhsot.
Sharing violation. I expect another software accesses the file at the same time in the background.

**Comment by mi-hol** [comment]
> Sharing violation. I expect another software accesses the file at the same time in the background.

Installers for Windows handle this situation by:
1. retry after a few seconds
2. if it still fails, the schedule replacing file at next boot.
Would that work for Android too?


> I could replace the sentence: "Is there no space left on the device?" with "Is the file system corrupted?"

Thanks. 

Looking further I wonder if the error text just below the change https://github.com/uholeschak/ediabaslib/commit/9cdbe53c1bbde1793846efccc96c45f1f2adc0e0#diff-edd0e096b54aaced05b92f2752582621b5806679d949823f0e02925fbad9d276R152
should get the same or similar change?

**Comment by uholeschak** [comment]
There is already special handing for protection software file locks.
But these are many files and this is simply too much for most protection software. This is why there is the hint to remove the software.
Yes the text below is the change.
