### ISSUE TITLE
Check and correct date and time of ECU at startup

### ISSUE THREAD

**Issue by mi-hol** [uholeschak/ediabaslib#134]
A great enhancement would be check date and time of ECU at startup and if different from smartphone, ask user if it should be corrected.

Background:
I changed battery of car, so it resetted date and time of ECU to a default.
Manual correction via buttons is cumbersome and I ended up with a wired time stamp in OBD Error report of "Date: 2075.14.29"

**Comment by uholeschak** [comment]
Who should this be done? There are many ECUs in the vehicle and the handling for this if always different.
Solution: Enable to use network time sync in your vehicle.
