### ISSUE TITLE
logo design for deep OBD application

### ISSUE THREAD

**Issue by harunbadilli** [uholeschak/ediabaslib#14]
I designed a logo for the deep OBD application. I was inspired by the letter "D". Color options, whether you want a single color or dual color as you want to send the format you want to prepare. I think the new logo of the application will be more noticeable. I hope you like it.

![1](https://user-images.githubusercontent.com/34319922/38993493-7b50dfda-43ec-11e8-97e9-bdac4cffa319.png)

![2](https://user-images.githubusercontent.com/34319922/38993494-7b7f2250-43ec-11e8-9923-5823a2365c91.png)

![3](https://user-images.githubusercontent.com/34319922/38993495-7bac86e6-43ec-11e8-8538-4144a43d2800.png)

![4](https://user-images.githubusercontent.com/34319922/38993496-7bdca0ec-43ec-11e8-91b0-1f9a81a70150.png)

**Comment by harunbadilli** [comment]
The files you want on the link is ready.
https://drive.google.com/open?id=1Gojc9u4ZrU3XCZuRRp3_E4EbsXqQwkBL

**Comment by uholeschak** [comment]
Thanks,
basically I have checked the files, but there are some problems.
- EdiabasLibConfigTool AppIcon must be an .ico file, please check the original one which sizes and formats it has to contain.
- The ic_stat_obd files have be use a special format:
https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar.html
There is also an generator for these files:
https://romannurik.github.io/AndroidAssetStudio/icons-notification.html
All files could only be used if they follow the specification, format and size exactly.

For general application icons there are these guidelines:
https://material.io/guidelines/style/icons.html#icons-product-icons
There seems to be now a new type of icon:
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
General guidelines:
https://developer.android.com/guide/practices/ui_guidelines/icon_design.html

Regards,
Ulrich

**Comment by harunbadilli** [comment]
First of all, I'm sorry I'm late. I made the arrangements and I sent a pull request.  https://github.com/uholeschak/ediabaslib/pull/16

**Comment by uholeschak** [comment]
Thanks, should be now all updated.
