### ISSUE TITLE
Connect to ELM327 Deep OBD WiFi (ESP8266) with STA mode.

### ISSUE THREAD

**Issue by shar34** [uholeschak/ediabaslib#140]
I create WiFi access point on Android device and connect ESP8266 adapter to this network. I can get web interface, but in Deep OBD application there is no IP address manual setting:
![1](https://user-images.githubusercontent.com/57906561/214067052-a09c5696-6e94-4468-85dd-9c799597c96a.jpg)
![2](https://user-images.githubusercontent.com/57906561/214067076-f20007d6-b3a4-45bc-a781-a532ccd9f120.jpg)

If I connect Android device directly to ESP8266 WiFi point, buttons "read" and "device configurations" become available. Is possible set manual IP address (192.168.236.154 like my photo for example) when Android device in WiFi access point mode?

**Comment by uholeschak** [comment]
At the moment I am working to set the IP and port in the GUI manually. Then you could set any IP address for the adapter you want.

**Comment by shar34** [comment]
I'll be waiting, thank you very much!

**Comment by uholeschak** [comment]
In the current Beta there is the possibility to edit the adapter IP address and port in the menu. In Hotspot mode (AP on, WiFi off), you must enter the adapter assigned IP address and port otherwise communication will not start.
There is no official support in Android for Hotspot mode in the app, so there is no guarantee that this will work.

**Comment by shar34** [comment]
Tried on Android multimedia headunit, everything works well, thanks!
![5](https://user-images.githubusercontent.com/57906561/215292901-abaa08b1-33cb-4eb7-a526-193e27b0d64d.jpg)

Maybe set port to **23** by default (in ELM327 Deep OBD WiFi ESP8266EX manual device configuration)?

**Comment by uholeschak** [comment]
Thanks for the info. You mean in Hotspot mode the default port is 23? Are there other WiFi devices that could be used in Hotspot mode that have a different port?

**Comment by shar34** [comment]
ESP-Link use 23 port by default in serial bridge: `In order to connect through the esp-link to a microcontroller use port 23.`
![Screenshot_20230129-133927_Deep_OBD](https://user-images.githubusercontent.com/57906561/215320695-9d65d75b-6c14-4616-a376-f46f764a6f55.png)

**Comment by uholeschak** [comment]
Yes I know, but the IP edit is also intended for other WiFi adapters in non Hotspot mode. All other adapters use port 35000. 
What I could perhaps do: If the port is missing and Hotspot mode is active, the default port would switch to 23, because only ESP is able to work in Hotspot mode.

**Comment by uholeschak** [comment]
In the next beta the default port in hotspot mode is 23 (if not specified).
