### ISSUE TITLE
Refreshing rate

### ISSUE THREAD

**Issue by angarsa15** [uholeschak/ediabaslib#142]
Hi, I recently received the obd2 with the firmware, and I would like to use it as a trip computer on my golf IV with KW1281 protocol, but I see that the refreshing rate of the real time values is so large. There is any possibility to change it and put it in something similar to a real time refreshing rate?
Thanks!

**Comment by uholeschak** [comment]
The only way is to reduce the amount of data to read. Only access one ECU and one data item of it.
