### ISSUE TITLE
E-Series MOST Gateway/CHAMP cannot be fully accessed

### ISSUE THREAD

**Issue by hanynowsky** [uholeschak/ediabaslib#145]
In the case of a BMW E60 LCI N52N equipped with MASK-II (MOST gateway / Champ), the access is not full and sometimes DeepOBD is unable to read IDrive data.
I guess it is because the KLINE/DCAN USB cable does not support the optical loop of the MOST gateway!
Is there any other cable that can be used with DeepOBD for a full support of the E60 LCI MOST Gateway?

Thanks Ulrich.

**Comment by uholeschak** [comment]
Have you send a trace file? App ID?
At least if it only sometimes fails this seems to be a sporadic communication error.
