### ISSUE TITLE
BMW ADS Inteface

### ISSUE THREAD

**Issue by dimiras** [uholeschak/ediabaslib#146]
Does this library make communication possible with BMW ADS modules without the need of an ADS interface?

**Comment by uholeschak** [comment]
I think this will be only possible with a Deep OBD Bluetooth adapter.
Mybe very very old protocols are not implemented.

**Comment by dimiras** [comment]
Would it be possible to use an usb INPA cable?

**Comment by uholeschak** [comment]
At least using an old ADS interface will create problems.
If your protocols don't require an ADS interface of course you could use an FTDI USB adapter.

**Comment by dimiras** [comment]
I dont have an ADS Interface just a USB INPA cable like this one https://www.ebay.com/itm/185713725007
I want to use this on a BMW Z3 (E36/7) to program the OBC.
Do you think I can program it with this lib and cable?

**Comment by uholeschak** [comment]
I think E36 is only using DS2, if you don't have a special ECU. Simply try.

**Comment by dimiras** [comment]
Ok Thanks
