### ISSUE TITLE
Can't program - unknown device 0xffe0

### ISSUE THREAD

**Issue by ba114** [uholeschak/ediabaslib#147]
Having some issues working with my dongle.

Ive purchased an item identical to that used in the instruction:
[Replace ELM327 firmware](https://github.com/uholeschak/ediabaslib/blob/master/docs/Replace_ELM327_HC04_Firmware.md)
The device has the same header pins, and i have connected the same way as well.

Using option 1: MPLAB IPE and selecting PIC18F25K80 identifies the PICkit3 that im using however then after reporting "target voltage detected" it errors out with "Target Device ID (0xffe0) is an Invalid Device ID. Please check your connections to the Target Device."

I havent been able to find much information on this other than potentially having [ruined the PICKit3 by feeding 12v to the Vdd pin](https://www.eevblog.com/forum/microcontrollers/pickit3-not-working/), however this is what the instructions say.

Have i missed something or are there missing steps in the instructions for how to correctly wire the PICKit3?

**Comment by uholeschak** [comment]
Basically if PIC connection is correct and there is no external load on the programming pins it should work.
But of course it must be a real PIC and no fake, which sometimes look identical.
Check very connections to the processor and use an oscilloscope see if the signals are valid.

**Comment by ba114** [comment]
The notes under the image on the instructions say that the VDD pin should be 5V how do i do that? It gets 12v from the OBD adapter when it is powered.

**Comment by uholeschak** [comment]
Basically this description has been supplied by another user, so I don't know the details of his hardware.
The PIC processor itself has a 5V power supply, you have of course use this PIC voltage and not the OBD voltage!
