### ISSUE TITLE
Bad ELM response with ELM327 V1.5 firmware

### ISSUE THREAD

**Issue by igogo2** [uholeschak/ediabaslib#153]
I'm getting errors while I'm using adapter with [ELM327 V1.5 firmware](https://github.com/uholeschak/ediabaslib/blob/master/docs/Replacement_firmware_for_ELM327.md#elm327-v15-firmware) in [ddt4all software](https://github.com/cedricp/ddt4all).
SubFunction Not Supported
Service Not Supported In Active Diagnostic Mode
![elm error](https://github.com/uholeschak/ediabaslib/assets/6361239/35459613-1e6e-4603-add4-47dfa27a9037)
Logs.
[ecu_ddt.log](https://github.com/uholeschak/ediabaslib/files/12014189/ecu_ddt.log)
[elm_ddt.log](https://github.com/uholeschak/ediabaslib/files/12014191/elm_ddt.log)

**Comment by uholeschak** [comment]
This is the standard ELM327 firmware, basically unmodified and it could not be changed.
You have to contact the manufacturer of ddt4all to fix this problem.
