### ISSUE TITLE
DeepOBD - 'Store log data settings' in Global Settings not working

### ISSUE THREAD

**Issue by gresmot** [uholeschak/ediabaslib#154]
Hi

Firstly thanks for making DeepOBD - it's an excellent app!

I am running the latest beta 1.3.169 on Android 11 and have 'Store log data settings' ticked in Global Settings as I would like to keep 'Log data' ticked in the Data logging menu. 

Whenever DeepOBD is closed and re-opened, if I go into the Data logging menu 'Log data' isn't ticked - it's not remembering/storing this setting.

Steps to re-reproduce:

Enable 'Store log data settings' in Global Settings
Open Data logging menu and tick 'Log data'
Close DeepOBD app
Re-open DeepOBD app
Open Data logging menu - Log data isn't ticked

Happy to supply any more information needed.

Thanks in advance.

**Comment by uholeschak** [comment]
This is intention, to prevent store overflow. You have to enable store of the stetting explicitly in the global settings, if you know what you are doing ...

**Comment by uholeschak** [comment]
Thanks, yes our are right, the settings are restored correctly with this option, but they are never saved ...

**Comment by uholeschak** [comment]
Should be fixed now.
