### ISSUE TITLE
Deep OBD error "Download failed because the resources could not be found"

### ISSUE THREAD

**Issue by danielsokolowski** [uholeschak/ediabaslib#161]
As per the tile, the app fails on first run...

**Comment by uholeschak** [comment]
More details are needed to reproduce this:
* App version
* Android version
* Custom Rom?
* Installed form Google Play? Other way?
* What are the exaction conditions to reproduce this
* Video or screenshots

**Comment by uholeschak** [comment]
At least this means you have a problem with your GooglePlay account.
