### ISSUE TITLE
How to use EdiabasTest.exe format

### ISSUE THREAD

**Issue by chaooe** [uholeschak/ediabaslib#162]
I am trying to use EdiabasTest.exe to run job, but i want to format the output of the job result.
I tried: 
`C:\EC-Apps\EdiabasTest\EdiabasTest.exe -f IGNITIONHISTORY=json -s PRG -j status_dlt_ip_configuration`
but the value of IGNITIONHISTORY is still the same as below
`IGNITIONCURRENT: I: -1 0xFFFF`

How to modify the format?

**Comment by chaooe** [comment]
got the format from the code, using the regular express to filter them
<img width="776" alt="image" src="https://github.com/uholeschak/ediabaslib/assets/12910117/b4c9bbfc-9642-4cc0-ba6a-18c9c296a71a">

**Comment by uholeschak** [comment]
You could of course also modify EdiabasTest.exe if you want, adding new arguments ...

**Comment by chaooe** [comment]
> You could of course also modify EdiabasTest.exe if you want, adding new arguments ...

Thanks, you are right. it would be prefect. i will have a try first.
