### ISSUE TITLE
Full INPA functionality with Deep OBD adapter?

### ISSUE THREAD

**Issue by horego** [uholeschak/ediabaslib#163]
Hey there,

i have a question regarding the inpa compatibility of the "Deep OBD" adapter.

After the patching process described in the installation documentation.
* Are there any restrictions when using this adapter with inpa?
* Is there a risk or already known that sth. will not work?

Best regards

**Comment by uholeschak** [comment]
The Ediabas completely replaced by EdiabasLib.
If you detect a bug in EdiabasLib, you could of course fix it, it's open source.

**Comment by horego** [comment]
@uholeschak thx for your fast reply.

i'm not familiar with automotive stuff so tbo i don't understand all the different words (or impact of replacing "ediabas").
My question is more like a end user question.

So what are the risks or known issues (if there are any) if i replace Ediabas with EdiabasLib when using inpa?

**Comment by uholeschak** [comment]
I understand, you want a general "there is absolutely no risk answer", but you will not get it.
Simply try it and if you have a problem report it.
