### ISSUE TITLE
ELM327 1.5 with yc1021

### ISSUE THREAD

**Issue by nopbit** [uholeschak/ediabaslib#165]
Hello all,

I have exactly same ELM327 like in the link below. Only difference is mine has 24c64 as yc1021 eeprom. I tried to change the pair key via editing original dump but it is still 1234. (Changed address 0x18F0). Do you have any how to secure the device? Thanks

[obd2dump.zip](https://github.com/uholeschak/ediabaslib/files/13765642/obd2dump.zip)

https://github.com/uholeschak/ediabaslib/blob/master/docs/Replace_Elm327_BT_Mini_Firmware.md#step1-program-the-yc1021-bt-settings

![elm327](https://github.com/uholeschak/ediabaslib/assets/31405701/36a013c1-bdba-4c84-b5a5-082a1885f186)

**Comment by uholeschak** [comment]
If this is the working solution I would close it. I can't test it because I have no such device.
