### ISSUE TITLE
F series coding 

### ISSUE THREAD

**Issue by craigea** [uholeschak/ediabaslib#167]
Quick question regarding coding on F-series, is it possible to code simple items such as start stop behavior, for example:

Auto Start/Stop Default OFF:

	3023? TCM_MSA_DEFAULT_OFF = aktiv 01

Auto Start/Stop Remember Last Setting:

	3023? TCM_MSA_MEMORY = aktiv 01
	
If so, which menu leads me to coding of these options.   The only menu giving access to CAS (Front Electronic Module) is "After the exchange", but it does not give option to drill into "Funktionen".  Or do I need to create my own custom menu somewhere?

<img width="340" alt="Screen Shot 2024-01-23 at 9 31 30 AM" src="https://github.com/uholeschak/ediabaslib/assets/65868243/e9f354b7-e1ac-4583-88b9-d9c9437c4611">

**Comment by uholeschak** [comment]
These are the options available in ISTA-D, this is high level only.
You have to use other tools fail more detailed modifications.
