### ISSUE TITLE
Does it have an exe for decode the SGBD file

### ISSUE THREAD

**Issue by chaooe** [uholeschak/ediabaslib#168]
I saw a FileDecoder in Tools folder, but i try to donet run failed due to below error
`
C:\Program Files\dotnet\sdk\8.0.101\Microsoft.Common.CurrentVersion.targets(2382,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "ICSharpCode.SharpZipLib, Version=1.3. 
ors. [C:\Users\AlexZhao\Downloads\ediabaslib-master\Tools\FileDecoder\FileDecoder\FileDecoder.csproj]
C:\Program Files\dotnet\sdk\8.0.101\Microsoft.Common.CurrentVersion.targets(2382,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "zlib.managed, Version=1.0.1.0, Cultur 
e=neutral, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\AlexZhao\Downloads\ediabaslib- 
master\Tools\FileDecoder\FileDecoder\FileDecoder.csproj]
C:\Users\AlexZhao\Downloads\ediabaslib-master\Tools\FileDecoder\FileDecoder\Program.cs(10,7): error CS0246: The type or namespace name 'Els_kom' could not be found (are you missing a using directive or an 
C:\Users\AlexZhao\Downloads\ediabaslib-master\Tools\FileDecoder\FileDecoder\Program.cs(11,7): error CS0246: The type or namespace name 'ICSharpCode' could not be found (are you missing a using directive o 
r an assembly reference?) [C:\Users\AlexZhao\Downloads\ediabaslib-master\Tools\FileDecoder\FileDecoder\FileDecoder.csproj]
C:\Users\AlexZhao\Downloads\ediabaslib-master\Tools\FileDecoder\FileDecoder\Program.cs(12,7): error CS0246: The type or namespace name 'ICSharpCode' could not be found (are you missing a using directive o 
r an assembly reference?) [C:\Users\AlexZhao\Downloads\ediabaslib-master\Tools\FileDecoder\FileDecoder\FileDecoder.csproj]
`

**Comment by uholeschak** [comment]
Probaby you are missing a nuget package.
This is for special VAG files. I think it will not help you.
