### ISSUE TITLE
Enet Wifi adapter

### ISSUE THREAD

**Issue by MasterZer01** [uholeschak/ediabaslib#17]
I need to set it up again bcs pc swap, can you help with files for Ista-D ?

**Comment by uholeschak** [comment]
What exactly do you mean? Does this help?
https://github.com/uholeschak/ediabaslib/blob/master/docs/ENET_WiFi_Adapter.md#use-the-adapter-with-inpa-tool32-or-ista-d

**Comment by MasterZer01** [comment]
i need that patch tool or files

**Comment by uholeschak** [comment]
You could download it from here:
https://github.com/uholeschak/ediabaslib/releases/tag/binaries_20180420

**Comment by MasterZer01** [comment]
Thanks mate !!!
