### ISSUE TITLE
ELM327 Bluetooth adapters does not send any commands to the K-Line (7 pin OBD)

### ISSUE THREAD

**Issue by ordu7** [uholeschak/ediabaslib#170]
Good day. Thank you very much for your grate work!!!
But I need your help. I flashed ELM327 Bluetooth adapters based on PIC18F25K80 microcontroller with Replacement firmware for ELM327 (default: For unmodified ELM327L adapter with any Bluetooth chip. Baud rate 38400)
After that adapter defined by v/0.15 by EdiabasLibConfigTool.exe, and DeepOBD application.
Additionally I can flash my adapter through the DeepOBD application to improved ELM327 V1.5 firmware and after that to Deep OBD replacement firmware over Bluetooth again.
But when I try to read the car, on K-line pin there are no any signals.
It looks like the DeepObd application sees the adapter and communicates with it, but does not send any commands to the K-Line (7 pin OBD).
Please can You help me.

**Comment by uholeschak** [comment]
Basically the K-LINE and L-LINE is working. Maybe your hardware ist not suitable for the firmware and has to be adapted.
In **automatic** mode K-LINE is only used if there is **NO CAN** signal present!

**Comment by ordu7** [comment]
Thank you for your answer. 
When I flash my adapter with improved ELM327 V1.5 firmware through DeepObd app, and use any app for car diagnostics I observe signals on pin 7 my adapter. That's why I think hardware of my adapter able to send commands to pin 7.
Additionally when I try to change Can mode option from automatically to k-line in DeepObd app, I have error A communication error occurred. But same time DeepObd app connected to my adapter. ((((

**Comment by ordu7** [comment]
Additionally want to say, that test with 82 F1 F1 FE FE 60 command successful passed

**Comment by uholeschak** [comment]
This means with automatic mode it is working? The you are using CAN. The protocol is specified by the ECU file. Are you using an ECU file with DS2 protocol?

**Comment by ordu7** [comment]
First of all, thank you for your patience and help. 
1. I have adapter based on PIC18F25K80 with with Replacement firmware for ELM327 (default Baud rate 38400)
2. EdiabasLibConfigTool.exe, and DeepOBD application defines my adapter (ver. 0.15) 
3. Test with 82 F1 F1 FE FE 60 command successful passed, I received echo
4. I can reflash my adapter through DeepObd app. to improved ELM327 V1.5 firmware and after that to Deep OBD replacement firmware over Bluetooth again without any error. All looks like working good, but. --->
5. When I try to connect to my car using DeepObd app, Inpa, Testo, no any signals from pin 21 of pic18f25k80 going to pin 7 OBD2, I use Oscilloscope. 
6. When I flash my adapter with improved ELM327 V1.5 firmware through DeepObd app, and use any app for car diagnostics I observe signals on pin 7 my adapter. That's why I think hardware of my adapter able to send commands to pin 7.
7. When I flash my adapter through DeepObd app again with modified Deep OBD firmware, and try to connect to my car no any signals on pin7 again. 
8. DeepObd app. when I try to change Can mode option from automatically to k-line till 03/2007 and press button Save in DeepObd app, I have error "A communication error occurred". But same time DeepObd app connected to my adapter.
___________________________________
Based on the above it looks like communication between DeepObd app, Bluetooth and pic18f25k80 present, but no any signals transmitted from pic18f25k80 to pin 7 (k-line) during scanning my car.

**Comment by ordu7** [comment]
Thank you for answer. 
Please can you explain me, if my Bluetooth chip has a problem, why DeepObd app. can reflash my adapter through Bluetooth, and can read firmware version on my adapter?

**Comment by uholeschak** [comment]
At least fix problem 8 first. Then try again.

**Comment by ordu7** [comment]
Thank you.
