### ISSUE TITLE
automatic generation of multiples tabs of the same ECU

### ISSUE THREAD

**Issue by jectx10** [uholeschak/ediabaslib#171]
Hello! many thanks for your fantastic application.
I would like to know if it is possible to have , using the AUTOMATIC generator, several tabs "FOR THE SAME ECU". I was able to create several tabs for different control units  (for example one tab for ECU DPF, second tab for air conditioning..) but I would like to be able to generate 3 or 4 tabs relating to the engine ECU (for example, 1 tab for DPF, other for injector adaptations and values, other tab for engine temperature...). 
Many thank!

**Comment by uholeschak** [comment]
You could do this manually by editing the page file. Here is an example:
https://github.com/uholeschak/ediabaslib/blob/master/BmwDeepObd/Xml/E61R/Combined.ccpage
**Warning**: This is extremely slow because the ECU file has to be permanently reloaded. Not recommended!
