### ISSUE TITLE
Modified LED configuration question

### ISSUE THREAD

**Issue by netdoggy** [uholeschak/ediabaslib#172]
The documentation constantly mentions some kind of elm327 "with modified LED configuration"

I spent a lot of time looking for information and understanding what exactly this meant, but I couldn't.
Is there any more detailed description of how to understand that I have a standard LED configuration or a modified one? :)

Thx

**Comment by uholeschak** [comment]
I have added the LED configuration for the adapter types in the docs

**Comment by netdoggy** [comment]
Thank You
