### ISSUE TITLE
Readme not up to date?

### ISSUE THREAD

**Issue by windev92** [uholeschak/ediabaslib#174]
Hello Ulrich,

The readme here https://github.com/uholeschak/ediabaslib/tree/master/BmwDeepObd

is telling to rename things in the Config directory, but there is no Config directory
Bests

**Comment by uholeschak** [comment]
Thanks for the info, the file is old and garbage. Deleted now.

**Comment by windev92** [comment]
So it means we don't need to configure anything regarless of the car?
Cause the app works a treat! I left it opened at home, then put an otg cable and plugged it to the car. The app detected in the background that it is usb and needs to be using ftdi with a notif!
Then it worked the first shot and got the VIN!

**Comment by uholeschak** [comment]
The file was a hint that the sample files are for one specific vehicle only. The correct way is to use the configuration generator.
