### ISSUE TITLE
Connect EdiabasLib:6801

### ISSUE THREAD

**Issue by aosbmw** [uholeschak/ediabaslib#178]
How can i do it? 
Start Ista do diag + open nsc expert for coding (like interface=remote, port = 6801 in ediabas.ini)

**Comment by uholeschak** [comment]
Sorry I don't understand what is your problem. The configuration is possible in the EdiabasLib.config file:
https://github.com/uholeschak/ediabaslib/blob/master/docs/EdiabasLib.config_file.md
If you are using a Deep OBD adapter you should use the EdiabsLibConfig tool. This will configure the file correctly.

**Comment by aosbmw** [comment]
I want use NETMAN server ifhsrv32.exe with EdiabasLib.  But if i replace orig dll api32.dll
ifhsrv32.exe not start.

**Comment by uholeschak** [comment]
Use an https://github.com/uholeschak/ediabaslib/blob/master/docs/ENET_WiFi_Adapter.md#alternative-wifi-adapter and the Config tool https://github.com/uholeschak/ediabaslib/releases
