### ISSUE TITLE
ELM327 BT Connection

### ISSUE THREAD

**Issue by colaas** [uholeschak/ediabaslib#18]
I have an ELM327 Bluetooth adapter that reports version 1.5 but doesn't actually support anything above 1.4 (I checked with ELM327 Identifier). When I connect with the Deep OBD android app, the connection just drops every couple of minutes for a minute or so. Is this the adapter's fault?
Also if I switch to another app and come back it always says there have been errors and wants to send a log file. Should I do it each time?

**Comment by uholeschak** [comment]
Write you AppId from the main menu here and send me a trace file, the I could check it.

**Comment by colaas** [comment]
The AppId is bcd26f7f-566e-46a1-88aa-e7667a49e6fe , there should already be some traces from weeks ago. I will send new ones as soon as I can.

**Comment by uholeschak** [comment]
I found 2 traces, the communication with the ELM seems to be ok, but there is simply no response from the car, also for different ECUs.
It's difficult to guess what's the cause of the problem.
