### ISSUE TITLE
Current consumption in idle mode for a modified Elm327.

### ISSUE THREAD

**Issue by skleptik** [uholeschak/ediabaslib#180]
Hello ! I made myself a DEEP OBD according to your instructions, thank you for your work!
But after use, I noticed that the device does not have a low-power mode and the idle current is 23mA. Perhaps it is possible to upgrade the program to reduce energy consumption during idle time?

**Comment by uholeschak** [comment]
The device is already using the maximum possible power reduction that is possible in the processor.
The power is consumed by other parts of the hardware.
Use the power switch a the device to power down the device completely.
