### ISSUE TITLE
Is it possible to use this library with C++?

### ISSUE THREAD

**Issue by Noscka** [uholeschak/ediabaslib#181]
I'm planning on making a project that uses this library. I want to make the project in C++ and I see that the library comes with a C++ wrapper(?). My project is in CMake, and trying to add the library as a precompiled library results in "External Symbol" errors. So is there some sort of usage/setup guide? and if not, then how would I be able to set the project up?

**Comment by uholeschak** [comment]
This is designed to use the VS solution only.
