### ISSUE TITLE
ATMEGA162 update question.

### ISSUE THREAD

**Issue by twbro54l** [uholeschak/ediabaslib#187]
Hello,

So i've found a tutorial (yep, i know... i should contact the author of that but it's regarding something else, i think? http://blog.obdii365.com/2021/07/09/update-inpa-kdcan-cable-with-enhanced-firmware/ ) and i was wondering... Why flash Combined.hex instead of CanAdapter.hex? And, does the EEPROM need's changing too? (in avrdudess).

Thanks.

**Comment by uholeschak** [comment]
The Combined.hex is for initial flashing (with bootloader), the partial file only for update
