### ISSUE TITLE
Flashed ELM327 adapter type detection failed

### ISSUE THREAD

**Issue by WatchDogee** [uholeschak/ediabaslib#188]
![image](https://github.com/user-attachments/assets/3857fdcf-cd83-4040-b168-814502e8a967)
I flashed at24c32 with modified_v1,  flashed PIC with default, def115200 and yc1021

But with every PIC firmware, I can see, pair and connect to the adapter Deep OBD with pin 1234, but when I open the app and select adapter type, it shows the following message -

![Screenshot_20241030_171317_de holeschak bmw_deep_obd](https://github.com/user-attachments/assets/ad5b484a-2377-4935-a4d0-ba02ca7087f7)

**Comment by uholeschak** [comment]
This probably means Baudrate of the firmware is not matching the Baudrate of the YC1021.
Typically this 38400 and default firmware should be used.
