### ISSUE TITLE
Any plan to support the USB ELM327?

### ISSUE THREAD

**Issue by Conti93** [uholeschak/ediabaslib#189]
As per title, regarding the replacement firmware, I have an ancient wired ELM327 adapter, which to be fair I could just yank the MAX232 out of it and put an HC05 module in but... I don't really like bluetooth on PC.

If that's out of the question I'll search for a bluetooth module/ELM.
Thanks.

**Comment by Conti93** [comment]
> No this is not planned. USB is unstable in the vehicle, because of mass loops.

I was writing an EDIT, but you were faster lol. Btw: I'm a fucking idiot. I was thinking about the HC05, once connected it acts fully transparent so it should already work as an ISTA USB interface, given that I use a laptop disconnected from ground, right?

**Comment by uholeschak** [comment]
There is a COM port support in EdiabasLib. But only for standard USB Adapters mit Atmel processor.

**Comment by Conti93** [comment]
Isn't the HC05 used by the Deep OBD adapter also recognized as a COM interface?
![image](https://github.com/user-attachments/assets/2bc3098c-6f3d-4385-955e-0adf72f425e2)
