### ISSUE TITLE
DPF meters since regeneration

### ISSUE THREAD

**Issue by colaas** [uholeschak/ediabaslib#19]
I cannot find the value for the meters traveled since the last Diesel Particulate Filter regeneration. I have found exhaust temperature before DPF, pressure and other items related, but this one doesn't seem to be there and I can't understand German well. Can you point me in the right direction? 
It is the 6th from the bottom in this screenshot you made:
![DPF](https://raw.githubusercontent.com/uholeschak/ediabaslib/master/docs/README_AppMotorSmall.png)
Thanks

**Comment by uholeschak** [comment]
That's difficult to tell, it depends from your ECU type. You could use the Yandex translation.

**Comment by colaas** [comment]
I have tried using Yandex but it is blocked after 24 hours. They want my mobile number.
I will try those, thanks.

**Comment by uholeschak** [comment]
The Yandex translation is also blocked after a certain amount of translations per time, the you have to wait.

**Comment by colaas** [comment]
Thanks! I found it.
Can I ask you what STAT STRECKE BEI ERFOLGREICHER REGENERATION WERT is? It looks like it is 10000km in the future.
Yandex/Google translate are not very clear!

**Comment by uholeschak** [comment]
This means the distance after successful regeneration,
I expect its the distance until the next regeneration will occur.

**Comment by colaas** [comment]
Is it odometer reading when it will force regeneration if it has not run?
This is the value, car has 169k km:
![regen](https://user-images.githubusercontent.com/12163378/39971116-616c4a9c-56f6-11e8-8c81-2b8033ead01e.png)

**Comment by tkosig** [comment]
It returns the odometer reading when the last successful regeneration happened.

**Comment by uholeschak** [comment]
I expected that.

**Comment by colaas** [comment]
It reads 178036754.233987 but my car has 169000km. Last successful regeneration was 5km ago.

**Comment by uholeschak** [comment]
Then it seems that the assumption was incorrect.
