### ISSUE TITLE
Ediabaslib voltage spoofing Ubatt for ISTA

### ISSUE THREAD

**Issue by Conti93** [uholeschak/ediabaslib#190]
Currently using Ediabaslib with ISTA 4.32.15 on Win10, bluetooth ELM interface reprogrammed with default firmware.
Is there a way to circumvent this error regarding the ignition & battery voltage (I get the former one in other areas)?
![image](https://github.com/user-attachments/assets/435a3420-b481-4bce-ba9c-a6e5ffbb0a05)

I tried node's voltage control to no avail. Maybe I'm missing something stupid?

Thank you.

**Comment by uholeschak** [comment]
This is a know ISTA problem unrelated to Ediabas. You have to patch ISTA for this or modify the ISTA configuration settings.
