### ISSUE TITLE
Android App cannot find WiFi adapter OBD2

### ISSUE THREAD

**Issue by Asaris69** [uholeschak/ediabaslib#21]
Hi,

I have got an adapter (WiFi OBD2), which I use for communication for Carly. Unfortunately DeepOBD Android App on my Samsung S7 cannot establish connection via this adapter. S7 is connected to the adapter via WLAN.

Thanks for the help in advance.

Maris

**Comment by uholeschak** [comment]
More details are needed. What exactly fails? Is the adapter accepted but the communication fails?
If the car is not supporting CAN, communication is not possible.
Please send trace file and publish App ID.

**Comment by mark-sch** [comment]
According to Carly website, your generation 2 adapter has not much in common with ELM anymore. Probably every 5 Euro ELM327 is better choice.

http://support.mycarly.com/de/knowledge-base/kannst-du-die-original-adapter-von-carly-auch-fur-andere-apps-und-software-benutzen/

**Comment by Asaris69** [comment]
What exact adapters do I need:
First car: BMW F11 520D, from Oct, 2011
Second car: VW Golf 6 1.6 TDI, from Jul, 2010

**Comment by uholeschak** [comment]
The BMW F11 should work, VW is only experimental at the moment and not recommended.

**Comment by Asaris69** [comment]
do you mean this one?

**Comment by uholeschak** [comment]
Here is a supported adapter table:
https://github.com/uholeschak/ediabaslib/blob/master/docs/AdapterTypes.md

**Comment by mark-sch** [comment]
The ediabaslib adapter choice is getting really complex - so many options. Are there any testings with STM32 based adapters, like Launch EasyDiag? Since this could include any protocol on a single adapter without ELM hacks.

**Comment by uholeschak** [comment]
No they are not supported.
