### ISSUE TITLE
ELM327 Wifi wird nicht erkannt

### ISSUE THREAD

**Issue by Profex86** [uholeschak/ediabaslib#23]
Hallo, ich habe einen ELM327 WIFI Adapter von Carly

ip: 192.168.0.10
Port: 35000
Version 1.4b

Wird leider von der Ediabaslib nicht erkannt. Hätte es mit Ista benutzt.

Was muss ich an dem Adapter ändern, damit es funktioniert. lg

**Comment by uholeschak** [comment]
Das Konfigtool unterstützt nur die ELM Ersatzfirmware.
Sie müssen EdiabsLib.ini manuell editieren.

**Comment by Profex86** [comment]
Sie meinen EDIABAS.INI ? Gibt es denn eine Bespieldatei?

**Comment by uholeschak** [comment]
Hier gibt es eine Doku für die Parameter:
https://github.com/uholeschak/ediabaslib/blob/master/docs/EdiabasLib.config_file.md

**Comment by Profex86** [comment]
Danke das Sie schnell antworten. Ich habe Jetzt die Api32.dll und EdiabsLib.ini in Rheingold\Ediabas\BIN gepackt und 

        <add key="Interface" value="STD:OBD"/>
        <add key="EcuPath" value="E:\BMW\ISTA-D\Rheingold\Ecu"/>
        <add key="RetryComm" value="1"/>
        <add key="TraceBuffering" value="0"/>
        <add key="IfhTraceBuffering" value="1"/>
-->
        <add key="ObdComPort" value="ELM327WIFI"/>
        <add key="AdsComPort" value=""/>
        <add key="LockTrace" value="0"/>
        <add key="EnetRemoteHost" value="auto:all"/>
        <add key="ApiTrace" value="0"/>
        <add key="IfhTrace" value="0"/>
<!--
        <add key="ObdDtrTimeCorrCom" value="0.3"/>
        <add key="ObdDtrTimeCorrFtdi" value="0.3"/>
        <add key="ObdAddRecTimeout" value="20"/>
        <add key="ObdFtdiBitBang" value="0"/>

angepasst..

Der Adapter blinkt jetzt zumindest wenn Ista versucht das Fahrzeug zu identifizieren. Allerdings bleibt es bei VIN stehen....

Getestet an E36, E91, E93

lg

**Comment by uholeschak** [comment]
Die ELMs funktionieren nur mit Fahrzeugen die CAN verwenden. Kann also sein, das es bei Ihnen gar nicht geht.
Sie können IfhTrace auf 2 setzen, dann kann man im Trace die Ursache sehen ...

**Comment by Profex86** [comment]
Per Handy und dem besagten Adapter funktioniert aber alles (Codieren und DTC)
von Baujahr 97 bis Heute.

IfhTrace habe ich auf 2 gesetzt, aber nirgendswo wird eine Trace Datei erstellt.

ich benutze die Rheingold Version 4.11.32.

Also ich habe NUR Api32.dll und EdiabsLib.ini in Rheingold\Ediabas\BIN 
aus EdiabasLibConfigTool kopiert und angepasst..

Lg

**Comment by uholeschak** [comment]
Geht das mit Deep OBD oder nur mit anderen Apps? Mit Deep OBD geht es nur mit CAN.
Das Trace File wird im Trace Verzeichnis unterhalb von von Bin erstellt.

**Comment by Profex86** [comment]
Geht mit 

Windows: ScanmasterELM
iPhone: Mit allen Verfügbaren Apps zB Carly (BMWWhat), OBD Doctor, Car Scanner ELM, EOBD, IOBD2 und so weiter...

•Protokolle:
•SAE J1850 PWM (41.6 kbaud)
•SAE J1850 VPW (10.4 kbaud)
•ISO 9141-2 (5 baud init, 10.4 kbaud)
•ISO 14230-4 KWP (5 baud init, 10.4 kbaud)

**Comment by uholeschak** [comment]
Das ist zwar nett, hilft aber nicht.

**Comment by Profex86** [comment]
LockTrace war die lösung...


executeJob('d_cas.grp'): 'IDENTIFIKATION'
executeJob('d_cas.grp'): 'INITIALISIERUNG'
ELM CMD send: 'ATD'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATE0'
ELM CMD rec: 'ATE0
OK

>'
ELM CMD send: 'ATSH6F1'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATCF600'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATCM700'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATPBC001'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATSPB'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATAT0'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATSTFF'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATAL'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATH1'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATS0'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATL0'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATCSM0'
ELM CMD rec: '?

>'
*** ELM invalid response: '?

>'
ELM optional command 'ATCSM0' failed
ELM CMD send: 'ATCTM5'
ELM CMD rec: '?

>'
*** ELM invalid response: '?

>'
ELM optional command 'ATCTM5' failed
ELM CMD send: 'ATJE'
ELM CMD rec: '?

>'
*** ELM invalid response: '?

>'
ELM optional command 'ATJE' failed
StopFrequent
Stop comm thread
Frequent mode stopped
Stop comm thread
 (STD:OBD CommParameter Port=ELM327WIFI, CorrCom=0.3, CorrFtdi=0.3, RecTimeout=20, BitBang=False): 0000010F 0001C200 000004B0 00000014 0000000A 00000002 00001388 
Start comm thread
Answer length: 0000 0000
 (Send): 82 40 F1 1A 80 4D 
Send SF
ELM CMD send: 'ATSTFF'
ELM CMD rec: 'OK

>'
ELM CAN send: '40021A8000000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
 (Send): 82 40 F1 1A 80 4D 
Send SF
ELM send SPACE
ELM data mode not stopped: 
>
ELM CAN send: '40021A8000000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
SetError: EDIABAS_IFH_0009
Stop comm thread
 (STD:OBD CommParameter Port=ELM327WIFI, CorrCom=0.3, CorrFtdi=0.3, RecTimeout=20, BitBang=False): 0000010D 00002580 000001F4 00000019 00000014 00000000 00000002 00001388 
Start comm thread
SetError: EDIABAS_IFH_0041
executeJob Exception: Error occured: EDIABAS_IFH_0041
executeIdentJob Exception: executeJob
executeJob('g_zgw.grp'): 'IDENTIFIKATION'
executeJob('g_zgw.grp'): 'INITIALISIERUNG'
StopFrequent
Stop comm thread
Frequent mode stopped
Stop comm thread
 (STD:OBD CommParameter Port=ELM327WIFI, CorrCom=0.3, CorrFtdi=0.3, RecTimeout=20, BitBang=False): 00000110 0007A120 000003E8 00000000 00000000 000003E8 000003E8 000004B0 00000000 00001388 00000002 000003E8 00000000 0000000A 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 
Start comm thread
Answer length: 0000 0000
 (Send): 83 10 F1 22 F1 50 E7 
Send SF
ELM send SPACE
ELM data mode not stopped: 
>
ELM CAN send: '100322F150000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
 (Send): 83 10 F1 22 F1 50 E7 
Send SF
ELM send SPACE
ELM data mode not stopped: 
>
ELM CAN send: '100322F150000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
SetError: EDIABAS_IFH_0009
executeJob Exception: Error occured: EDIABAS_IFH_0009
executeIdentJob Exception: executeJob
executeJob('zgw_01.prg'): 'STATUS_VIN_LESEN'
executeJob('zgw_01.prg'): 'INITIALISIERUNG'
StopFrequent
Stop comm thread
Frequent mode stopped
Stop comm thread
 (STD:OBD CommParameter Port=ELM327WIFI, CorrCom=0.3, CorrFtdi=0.3, RecTimeout=20, BitBang=False): 00000110 0007A120 000003E8 00000000 00000000 000003E8 000003E8 000004B0 00000000 00001388 00000002 000003E8 00000000 0000000A 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 
Start comm thread
Answer length: 0000 0000
 (Send): 83 10 F1 22 F1 90 27 
Send SF
ELM send SPACE
ELM data mode not stopped: 
>
ELM CAN send: '100322F190000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
 (Send): 83 10 F1 22 F1 90 27 
Send SF
ELM send SPACE
ELM data mode not stopped: 
>
ELM CAN send: '100322F190000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
SetError: EDIABAS_IFH_0009
executeJob Exception: Error occured: EDIABAS_IFH_0009
executeJob('zcs_all.prg'): 'FGNR_LESEN'
executeJob('zcs_all.prg'): 'INITIALISIERUNG'
StopFrequent
Stop comm thread
Frequent mode stopped
Stop comm thread
 (STD:OBD CommParameter Port=ELM327WIFI, CorrCom=0.3, CorrFtdi=0.3, RecTimeout=20, BitBang=False): 00000006 00002580 00000044 00000000 00000000 000003E8 00000019 00000014 00000000 
Start comm thread
SetError: EDIABAS_IFH_0041
executeJob Exception: Error occured: EDIABAS_IFH_0041
executeInitJob Exception: executeJob
Stop comm thread
ELM send SPACE
ELM data mode not stopped: 
>
executeJob('d_0080.grp'): 'IDENTIFIKATION'
executeJob('d_0080.grp'): 'INITIALISIERUNG'
ELM CMD send: 'ATD'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATE0'
ELM CMD rec: 'ATE0
OK

>'
ELM CMD send: 'ATSH6F1'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATCF600'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATCM700'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATPBC001'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATSPB'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATAT0'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATSTFF'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATAL'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATH1'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATS0'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATL0'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATCSM0'
ELM CMD rec: '?

>'
*** ELM invalid response: '?

>'
ELM optional command 'ATCSM0' failed
ELM CMD send: 'ATCTM5'
ELM CMD rec: '?

>'
*** ELM invalid response: '?

>'
ELM optional command 'ATCTM5' failed
ELM CMD send: 'ATJE'
ELM CMD rec: '?

>'
*** ELM invalid response: '?

>'
ELM optional command 'ATJE' failed
StopFrequent
Stop comm thread
Frequent mode stopped
Stop comm thread
 (STD:OBD CommParameter Port=ELM327WIFI, CorrCom=0.3, CorrFtdi=0.3, RecTimeout=20, BitBang=False): 00000006 00002580 00000080 00000000 00000000 000001F4 00000019 00000014 00000000 
Start comm thread
SetError: EDIABAS_IFH_0041
executeJob Exception: Error occured: EDIABAS_IFH_0041
executeInitJob Exception: executeJob
executeIdentJob Exception: executeJob
Stop comm thread
executeJob('d_0010.grp'): 'IDENTIFIKATION'
executeJob('d_0010.grp'): 'INITIALISIERUNG'
ELM CMD send: 'ATD'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATE0'
ELM CMD rec: 'ATE0
OK

>'
ELM CMD send: 'ATSH6F1'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATCF600'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATCM700'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATPBC001'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATSPB'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATAT0'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATSTFF'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATAL'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATH1'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATS0'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATL0'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATCSM0'
ELM CMD rec: '?

>'
*** ELM invalid response: '?

>'
ELM optional command 'ATCSM0' failed
ELM CMD send: 'ATCTM5'
ELM CMD rec: '?

>'
*** ELM invalid response: '?

>'
ELM optional command 'ATCTM5' failed
ELM CMD send: 'ATJE'
ELM CMD rec: '?

>'
*** ELM invalid response: '?

>'
ELM optional command 'ATJE' failed
StopFrequent
Stop comm thread
Frequent mode stopped
Stop comm thread
 (STD:OBD CommParameter Port=ELM327WIFI, CorrCom=0.3, CorrFtdi=0.3, RecTimeout=20, BitBang=False): 00000002 00000000 00000010 00000000 00000000 000007D0 00000014 00000064 00000000 
Start comm thread
SetError: EDIABAS_IFH_0041
executeJob Exception: Error occured: EDIABAS_IFH_0041
executeInitJob Exception: executeJob
executeIdentJob Exception: executeJob
executeJob('d_lm.grp'): 'IDENTIFIKATION'
executeJob('d_lm.grp'): 'INITIALISIERUNG'
StopFrequent
Stop comm thread
Frequent mode stopped
Stop comm thread
 (STD:OBD CommParameter Port=ELM327WIFI, CorrCom=0.3, CorrFtdi=0.3, RecTimeout=20, BitBang=False): 0000010F 0001C200 000004B0 00000014 0000000A 00000002 00001388 
Start comm thread
Answer length: 0000 0000
 (Send): 82 70 F1 1A 80 7D 
Send SF
ELM CMD send: 'ATSTFF'
ELM CMD rec: 'OK

>'
ELM CAN send: '70021A8000000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
 (Send): 82 70 F1 1A 80 7D 
Send SF
ELM send SPACE
ELM data mode not stopped: 
>
ELM CAN send: '70021A8000000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
SetError: EDIABAS_IFH_0009
Stop comm thread
 (STD:OBD CommParameter Port=ELM327WIFI, CorrCom=0.3, CorrFtdi=0.3, RecTimeout=20, BitBang=False): 0000010D 00002580 000001F4 00000019 00000014 00000000 00000002 00001388 
Start comm thread
SetError: EDIABAS_IFH_0041
executeJob Exception: Error occured: EDIABAS_IFH_0041
executeIdentJob Exception: executeJob
executeJob('g_cas.grp'): 'IDENTIFIKATION'
executeJob('g_cas.grp'): 'INITIALISIERUNG'
StopFrequent
Stop comm thread
Frequent mode stopped
Stop comm thread
 (STD:OBD CommParameter Port=ELM327WIFI, CorrCom=0.3, CorrFtdi=0.3, RecTimeout=20, BitBang=False): 00000110 0007A120 000003E8 00000000 00000000 000003E8 000003E8 000004B0 00000000 00001388 00000002 000003E8 00000000 0000000A 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 
Start comm thread
Answer length: 0000 0000
 (Send): 83 40 F1 22 F1 50 17 
Send SF
ELM send SPACE
ELM data mode not stopped: 
>
ELM CAN send: '400322F150000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
 (Send): 83 40 F1 22 F1 50 17 
Send SF
ELM send SPACE
ELM data mode not stopped: 
>
ELM CAN send: '400322F150000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
SetError: EDIABAS_IFH_0009
executeJob Exception: Error occured: EDIABAS_IFH_0009
executeIdentJob Exception: executeJob
executeJob('frm_87.prg'): 'READ_FVIN'
executeJob('frm_87.prg'): 'INITIALISIERUNG'
StopFrequent
Stop comm thread
Frequent mode stopped
Stop comm thread
 (STD:OBD CommParameter Port=ELM327WIFI, CorrCom=0.3, CorrFtdi=0.3, RecTimeout=20, BitBang=False): 0000010F 0001C200 00000578 00000014 0000000A 00000002 00001388 
Start comm thread
Answer length: 0000 0000
 (Send): 83 72 F1 22 10 10 28 
Send SF
ELM send SPACE
ELM data mode not stopped: 
>
ELM CAN send: '7203221010000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
 (Send): 83 72 F1 22 10 10 28 
Send SF
ELM send SPACE
ELM data mode not stopped: 
>
ELM CAN send: '7203221010000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
SetError: EDIABAS_IFH_0009
executeJob Exception: Error occured: EDIABAS_IFH_0009
Stop comm thread
ELM send SPACE
ELM data mode not stopped: 
>
executeJob('ews3.prg'): 'FGNR_LESEN'
executeJob('ews3.prg'): 'INITIALISIERUNG'
ELM CMD send: 'ATD'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATE0'
ELM CMD rec: 'ATE0
OK

>'
ELM CMD send: 'ATSH6F1'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATCF600'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATCM700'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATPBC001'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATSPB'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATAT0'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATSTFF'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATAL'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATH1'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATS0'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATL0'
ELM CMD rec: 'OK

>'
ELM CMD send: 'ATCSM0'
ELM CMD rec: '?

>'
*** ELM invalid response: '?

>'
ELM optional command 'ATCSM0' failed
ELM CMD send: 'ATCTM5'
ELM CMD rec: '?

>'
*** ELM invalid response: '?

>'
ELM optional command 'ATCTM5' failed
ELM CMD send: 'ATJE'
ELM CMD rec: '?

>'
*** ELM invalid response: '?

>'
ELM optional command 'ATJE' failed
Stop comm thread
 (STD:OBD CommParameter Port=ELM327WIFI, CorrCom=0.3, CorrFtdi=0.3, RecTimeout=20, BitBang=False): 00000006 00002580 000000FF 00000000 00000000 000001F4 00000019 00000014 00000000 
Start comm thread
SetError: EDIABAS_IFH_0041
executeJob Exception: Error occured: EDIABAS_IFH_0041
executeInitJob Exception: executeJob
executeJob('d_zgm.grp'): 'IDENTIFIKATION'
executeJob('d_zgm.grp'): 'INITIALISIERUNG'
StopFrequent
Stop comm thread
Frequent mode stopped
Stop comm thread
 (STD:OBD CommParameter Port=ELM327WIFI, CorrCom=0.3, CorrFtdi=0.3, RecTimeout=20, BitBang=False): 0000010F 0001C200 000004B0 00000014 0000000A 00000002 00001388 
Start comm thread
Answer length: 0000 0000
 (Send): 82 00 F1 1A 80 0D 
Send SF
ELM CMD send: 'ATSTFF'
ELM CMD rec: 'OK

>'
ELM CAN send: '00021A8000000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
 (Send): 82 00 F1 1A 80 0D 
Send SF
ELM send SPACE
ELM data mode not stopped: 
>
ELM CAN send: '00021A8000000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
SetError: EDIABAS_IFH_0009
Stop comm thread
 (STD:OBD CommParameter Port=ELM327WIFI, CorrCom=0.3, CorrFtdi=0.3, RecTimeout=20, BitBang=False): 0000010D 00002580 000001F4 00000019 00000014 00000000 00000002 00001388 
Start comm thread
SetError: EDIABAS_IFH_0041
executeJob Exception: Error occured: EDIABAS_IFH_0041
executeIdentJob Exception: executeJob
executeJob('g_frm.grp'): 'IDENTIFIKATION'
executeJob('g_frm.grp'): 'INITIALISIERUNG'
StopFrequent
Stop comm thread
Frequent mode stopped
Stop comm thread
 (STD:OBD CommParameter Port=ELM327WIFI, CorrCom=0.3, CorrFtdi=0.3, RecTimeout=20, BitBang=False): 00000110 0007A120 000003E8 00000000 00000000 000003E8 000003E8 000004B0 00000000 00001388 00000002 000003E8 00000000 0000000A 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001 
Start comm thread
Answer length: 0000 0000
 (Send): 83 72 F1 22 F1 50 49 
Send SF
ELM send SPACE
ELM data mode not stopped: 
>
ELM CAN send: '720322F150000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
 (Send): 83 72 F1 22 F1 50 49 
Send SF
ELM send SPACE
ELM data mode not stopped: 
>
ELM CAN send: '720322F150000000'
ELM CAN rec: 'CAN ERROR'
ELM CAN rec: ''
ELM Data mode aborted
ELM CMD send: 'ATMA'
*** Receive timeout
*** No header received
SetError: EDIABAS_IFH_0009
executeJob Exception: Error occured: EDIABAS_IFH_0009
executeIdentJob Exception: executeJob
Stop comm thread
ELM send SPACE
ELM data mode not stopped: 
>
Stop comm thread

**Comment by uholeschak** [comment]
Dort steht:
ELM CAN rec: 'CAN ERROR'
Also ein Fahrzeug ohne CAN, geht also nicht.

**Comment by Profex86** [comment]
Hallo, beim F10 eben getestet, selber Fehler....
Ich habe eben ein altes Android Telefon ausgegraben um Deepobd zu installieren.. (Aus dem Playstore).. Soweit so gut, nachdem ich das Programm starte, sagt er mir, das er die ECU Daten entpacken muss.. Das ganze dauert dann ca. 10 Minuten und wenn er 100% erreicht hat, dann haut er eine Fehlermeldung raus, das die zip Datei fehlerhaft wäre.... Wo finde ich diese Zip Datei damit ich sie manuell entpacken und auf die SD Karte schieben kann? 

Liebe grüße

**Comment by uholeschak** [comment]
Die Datei kann man nicht manuell entpacken sondern ist im obb enthalten.
Verwenden Sie die aktuelle App Version 1.2.113? In der Version davor gab es ein Problem bei bestimmten Spracheinstellungen.

**Comment by Profex86** [comment]
Ja, eben nochmal neu aus dem PlayStoe geladen. Version 1.2.113.

Genaue Fehlermeldung;

Fehler
Das Entpacken der Dateien ist fehlgeschlagen.
Die Zip-Datei scheint beschädigt zu sein.

Wie gesagt, läuft erstmal bis 100% durch...

**Comment by uholeschak** [comment]
In welcher Phase tritt das auf? Beim Prüfen der Dateien oder noch beim entpacken?
Android Version?
Im Notfall können Sie mir mal ein Video nach ulrich@holeschak.de senden.

**Comment by Profex86** [comment]
Frage, die ECU Daten müssen entpackt werden (Größe ca. 2.3GB) ------->Daten vorbereiten------>Archiv vorbereiten-----> Fehler!

Wenn ich die App komplett deinstalliere und neu installiere, dann kommt er bis 100% Entpacken und dann der Fehler...

Android-Version 4.4.4

**Comment by uholeschak** [comment]
Also tritt das dann noch beim Archiv vorbereiten auf? Da werden die Daten entschlüsselt.

**Comment by Profex86** [comment]
Ja außer wenn ich die App komplett runter schmeiße und alles von vorne beginne, dann kommt er bis 100% entpacken.

**Comment by uholeschak** [comment]
Da ist jetzt schwierig zu sagen wo das Problem liegt.
Das Android ist auch schon sehr alt, können Sie das auf einem neueren Gerät probieren?

**Comment by Profex86** [comment]
Ja kann ich, ich probiere es gleich mal mit BlueStacks, wenn das nicht klappt, dann probiere ich es auf den Asus Tinker Board, mache da mal später Android zum testen drauf.

**Comment by Profex86** [comment]
Stimmt lag am Gerät. Diesen Adapter der angeboten wird, finde ich leider nicht bei ebay. Andere Möglichkeit zum kaufen?

Und vor allem, ist es voll kompatibel zu ista+ bzw Rheingold?
Lg

**Comment by uholeschak** [comment]
Wahrscheinlich gibt es den Adapter wieder in eine Woche, Sie müssen sich dann beeilen.
Sie müssen das Konfig Tool verwenden und die Installationen patchen.

**Comment by Profex86** [comment]
Gibt es denn irgendwo eine Möglichkeit den Adapter vorzubestellen?

**Comment by uholeschak** [comment]
Nein, das wäre für mich zu aufwendig.
