### ISSUE TITLE
Ediabas Lib BT Adapter with easy DIS 44 don`t work

### ISSUE THREAD

**Issue by 0NDevil** [uholeschak/ediabaslib#25]
Hi, i don`t know is it a error or not but i thought when INPA/Ediabas/Tool32/NCS Expert and DeepOBD work with the Bluetooth Adapter, it work with DIS because DIS use the Ediabas for Connection?!?

Did anyone try this connection before or managed it to work ?

Sorry for my bad english
I`m from Germany and had only 4years English in School..

**Comment by uholeschak** [comment]
DIS is untested and is not supported at the moment.
