### ISSUE TITLE
Clarify/expand on DS2 pin 7+8 connection

### ISSUE THREAD

**Issue by matt-ball** [uholeschak/ediabaslib#26]
I'm trying to find a bluetooth adapater for the E46. I can see that this falls under DS2 - however the current link in the README is for an expired auction and I'm not clear if the pin 7+8 connection is something I can buy off the shelf or requires some input from me? It would be good to improve the readme to include this detail. Thanks.

The reason for looking for a different adapter is because I received this message:
![image](https://user-images.githubusercontent.com/8490181/44808262-a630f980-abc3-11e8-84a3-fb7bf2b235d4.png)

**Comment by uholeschak** [comment]
I have written that I am in holiday, for more details read the Ebay text.

Am 29. August 2018 20:41:35 schrieb Matt Ball <notifications@github.com>:

**Comment by uholeschak** [comment]
Description updated
