### ISSUE TITLE
ELM WiFi ESP8266ex not detected by Deep OBD for BMW and VAG

### ISSUE THREAD

**Issue by bi42606** [uholeschak/ediabaslib#27]
Hello
First congratulate you for this project, it's a great job and I thank you for sharing it.
I have a problem with an ESP8266ex ELM WiFi adapter, in which I have modified both the ESP (esp-link Release 2.2.3) and the PIC18f25k80 firmware (115200bps esp8266 firmware), and now I can not connect using the Deep OBD for app BMW and VAG, the adapter seems not to receive the data, I think it is because the application does not try to connect by the ip 192.168.4.1 port 23, if so it is possible that it is included, or can be selected in the settings of the app
Greetings and thank you

**Comment by uholeschak** [comment]
Yes that's true, the adapter is not supported at the moment and I have no time to change this.
