### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [uholeschak/ediabaslib#28]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by uholeschak** [comment]
Thanks, if you want you could try.
The current icon has also been designed by somebody else.
Please check the repository for the different image formats and sizes, there are also monochrome variants.
Creating these variants requires most time, for some you have to read the android image specification, there are also android tools to convert the images.
In the final form also vector data is required to allow generation of other sizes.

**Comment by mansya** [comment]
hi sir. I already designed the logo for this project. I made the OBD word the real logo. How ? do you like it ? if yes please inform me. and if there are changes please tell me to
![ediabaslib](https://user-images.githubusercontent.com/33461607/47956237-02553700-dfd4-11e8-9f24-4733e886c2ad.png)
and about vector files and other variant icons. I always provide it. you can check my repo.

**Comment by uholeschak** [comment]
Thanks, basically I like it, but I will ask some other people in the next days first ...

**Comment by mansya** [comment]
can I continue to pull requests? if yes. I will give all files from this icon.

**Comment by uholeschak** [comment]
I think it's better if you wait, maybe some changes are required.

**Comment by mansya** [comment]
ok sir. I will wait for him.

**Comment by mansya** [comment]
hi sir. how about the continuation of this logo? does he like it?

**Comment by uholeschak** [comment]
Sorry I forgot about it in the meantime, at the moment I am very busy.
I have asked our designer, basically he thinks it's ok, but the mentioned that color gradients are not modern any more ...

**Comment by mansya** [comment]
hi sir, sorry about the long time. I am a little busy with my environment. so where is this color? and you can choose colors as you like between the four colors.
![ediabaslib](https://user-images.githubusercontent.com/33461607/49804588-d7849e00-fd4a-11e8-9324-528cfd2b305b.png)

**Comment by harryberlin** [comment]
looks a bit like BOSCH logo.

**Comment by uholeschak** [comment]
Perhaps it's best to keep the current logo at the moment, since we both have no real time to change it ...

**Comment by mansya** [comment]
if this logo is only found on the file [Resources](https://github.com/uholeschak/ediabaslib/tree/master/BmwDeepObd/Resources) and [Images](https://github.com/uholeschak/ediabaslib/tree/master/docs/Images) I can change it. then I can do pull requests. How ? do you want me to try it?

**Comment by uholeschak** [comment]
I think partially changing the logo makes no sense, it should be consistent.
Last time updating all locations was a work of several days, and had the bad the bad effect that,
that people did not find the app in the PlayStore any more.

**Comment by mansya** [comment]
if it impacts like that. it would be better to stay consistent with the old logo. Thank you sir
