### ISSUE TITLE
Missing file CanAdapterElm.X.production.hex?

### ISSUE THREAD

**Issue by doitauto** [uholeschak/ediabaslib#3]
Hi @uholeschak,

i am testing your project thx about but a little issue VS give me errors when i build the project
`/EDIABASLIB/ediabaslib-master/EdiabasLib/CanAdapterElm/CanAdapterElm.X/dist/default/production/CanAdapterElm.X.production.hex".' (CS1566) (BmwDeepObd)`
missing a file here on github?

**Comment by uholeschak** [comment]
You have to build the adapter hex files with MPLAB X IDE from
`EdiabasLib\CanAdapterElm\CanAdapterElm.X` or copy the files from the binary package.
