### ISSUE TITLE
ENET Adapter für F Modelle erwerben

### ISSUE THREAD

**Issue by lxha** [uholeschak/ediabaslib#30]
Hallo Herr Holeschak,
Wann stellen Sie wieder Adapter in ebay ein? Vielen Dank.

**Comment by uholeschak** [comment]
Eigentlich hatte ich das nicht mehr so schnell vorgehabt, da der Aufwand sehr groß ist und die BT Adapter bei F-Modellen auch funktionieren.

**Comment by uholeschak** [comment]
Können Sie ja mal probieren, ob das mit der App am Ende funktioniert kann ich nicht sagen ...
