### ISSUE TITLE
Does this support reading/writing to F-series DMEs?

### ISSUE THREAD

**Issue by brandonros** [uholeschak/ediabaslib#31]
https://gist.github.com/brandonros/3e4eb6b39d77e2e7469abdf44ab4c7f3

**Comment by brandonros** [comment]
?

**Comment by uholeschak** [comment]
Sorry I do not understand what you really want.

**Comment by brandonros** [comment]
I don't understand. You're obfuscating documentation + information on an open-sourced project?

**Comment by uholeschak** [comment]
No simply try ...
