### ISSUE TITLE
Only DTCs are shown no ECU-data

### ISSUE THREAD

**Issue by Tottback** [uholeschak/ediabaslib#32]
Hello, I'm using DeepOBD on a Huawei P10lite with Tacklife AOBD1W WiFi-Adapter on BMW E87.
Many thanks for this powerful App.
My issue is that the autogeneration find many ECUs and when connected I could see the failures on the errors-page but the ECU-sheets are empty (see screenshots). What am I doing wrong ?

![screenshot_20190126-120713](https://user-images.githubusercontent.com/39876346/51790277-38e5bc80-2193-11e9-8785-f2127bc70b4e.png)
![screenshot_20190126-120803](https://user-images.githubusercontent.com/39876346/51790278-38e5bc80-2193-11e9-90a8-a1e2bf7fe2c8.png)
![screenshot_20190126-120819](https://user-images.githubusercontent.com/39876346/51790279-397e5300-2193-11e9-8408-0dbab08ec497.png)

**Comment by uholeschak** [comment]
It seems that my old response dis not show up here:
Probably you don't have selected the jobs and results you want to see for the ecu on the ecu configuration page ...
