### ISSUE TITLE
QUESTION: Sample E61 configs not working?

### ISSUE THREAD

**Issue by esell** [uholeschak/ediabaslib#36]
First off, thank you for providing this, it has been a VERY helpful tool!

I just started playing around with the Deep OBD BMW app on my USA E61 and noticed many of the values from the sample E61 config were not being read on the "motor" tab. Is there something else I need to do or could it be a difference in the E61 build (USA vs Euro, year, etc)?

**Comment by uholeschak** [comment]
This is possible, the config is only fitting for my car, you have to create your own one.
First create a configuration with the configuration generator and then create a manual config with this data.
