### ISSUE TITLE
Read firmware version failed

### ISSUE THREAD

**Issue by sz00gun** [uholeschak/ediabaslib#37]
Hi, I'm trying to patch my MaxiScam OBDII 901 using EdiabasLib.exe however I get an error: 
**Connected
Read firmware version failed**

Any idea? A bug in a program? I have Skoda Superb 2014 FL 2.0 diesel. Please advise

![Clipboard03](https://user-images.githubusercontent.com/7549566/55265162-0168be80-526f-11e9-8b9c-15894a15de37.jpg)

**Comment by uholeschak** [comment]
You have to program it with a PIC programmer.
