### ISSUE TITLE
Not required  - Carista can do it without custom firmware

### ISSUE THREAD

**Issue by Isilder** [uholeschak/ediabaslib#43]
Custom firmware is technically Not required  - Carista can do it without custom firmware
What would be required is changing hte program to have deepodb work with unrecognised firnwares/devices.

Carista can do custom VAG settings  using standard ELM327
Not many, the ones with discrete  CPU and EEPROM matching original ELM327 hardware would be best. The cheap ones are implemented to work for standard ODB2 packets, probably having specification based on sniffing/reverse engineering standard ODB2 protocol converstion only.

If carista can do it with PP2145, standard firmware, then why do you *need* custome firmware.

In fact, since its hard to find the  elm327's that can be customised with the EEPROM/PIC programmer thing,  better to work with whats available ?  such as carista's list or the jaycar one

**Comment by uholeschak** [comment]
EdiabasLib is based on Ediabas and that is using special internal protocols.
Maybe there are some of them that could be implemented also by standard ELM,
if you want you could find out an implement this in the transport layer.
