### ISSUE TITLE
Problems E61 LCI

### ISSUE THREAD

**Issue by Timmmeyyy** [uholeschak/ediabaslib#57]
Hi I have some issues to read the ecus, i have an vgate icar2 tool. I tried to read the ecus on an bmw e61 lci build in late 2007.
 I take an screenshot, i pretty sure that my car dont have k-line, because its an lci. 
With the vgate tool and "bimmercode" its works quit fine also with the apps "torque" or "car scanner".  

With an other tool i have i can work without any problems with inpa and tool32 via usb and my notebook. 

Maybe, you have any ideas where my mistake is. 

Greetz Tim 
 
![Screenshot_20191218-175439](https://user-images.githubusercontent.com/41114947/71111776-62a03b80-21ca-11ea-9fcb-4e1f63e58fa0.png)

**Comment by uholeschak** [comment]
The screenshot does not help, send a trace file and publish your app id.

**Comment by Timmmeyyy** [comment]
Good Morning, how can i get the tracefile? Greetz Tim

**Comment by mark-sch** [comment]
With a little passion everyone is able to figure out. Ask valueable questions to the valueable time of Ulrich ;-) He is commiting awesome investigations to github atm.

**Comment by Timmmeyyy** [comment]
Figure it out, sorry for that stupid question :D. I will create it later an give you an feedback with that informations. Greetz Tim

**Comment by uholeschak** [comment]
You could simply send it with the app.

**Comment by Timmmeyyy** [comment]
Hi, i send you an email with the tracefile. The Screenshot below show the ID.

Greetz Tim 

![Screenshot_20191219-172240](https://user-images.githubusercontent.com/41114947/71194357-1289ad80-228c-11ea-9533-b5e92687771c.png)

**Comment by uholeschak** [comment]
What means email? If you send it with the app, it's stored in a database but there is nothing.

**Comment by uholeschak** [comment]
I the found the data now. Basically the detection is working in the first step, VIN and construction date is extracted correctly. But when trying to find the ECUs with a broadcast there is no response.

**Comment by Timmmeyyy** [comment]
Ah sorry no email my mistake :D. You have any idea what i can try else? Its is not the k-line problem, its dcan?

greetz

**Comment by uholeschak** [comment]
Perhaps you adapter has problems with the broadcast responses. There will be a flood of answers, maybe it's too much. Perhaps you should try with an USB FTDI adapter, this is more stable.

**Comment by Timmmeyyy** [comment]
My Dcan usb cable works fine with inpa. You have an alternativ wifi adapter which should work fine with your app an my car?

**Comment by uholeschak** [comment]
Not at the moment, but try the USB cable with the app. INPA not using broadcasts, is it working also with ISTA-D? Maybe the ECU for the broadcasts is damaged.

**Comment by Timmmeyyy** [comment]
I give you a feedback tomorrow . Greetz

**Comment by Timmmeyyy** [comment]
Hi with the usb cable it works pretty fine, so it is a Problem with the vgate tool? Before i bought it i see a lot of YouTube vids where people use this tool? I send you the tracefile today withe cable use.  Maybe you have an solution how can i use the vgate tool? Greetz Tim

**Comment by uholeschak** [comment]
Thanks for the info, but I see no solution for your adapter, you could only try to buy different ones.
