### ISSUE TITLE
IGN Voltage: Read RI pin

### ISSUE THREAD

**Issue by GTO2013** [uholeschak/ediabaslib#58]
Hi,
this is more like a nice-to-have improvement than an issue: In INPA the IGN and BATT dots dont work (in ADS mode). The IGN line is connected to the RI pin. I looked through your code and I think that you only use the DSR pin. Just wanted to report that here, pretty low priority problem :)

**Comment by uholeschak** [comment]
Yes this is possible, but at the moment I have no intention to change this, since ADS is very old. If you want, you could send a patch.
