### ISSUE TITLE
Tablet doesn't get a connection

### ISSUE THREAD

**Issue by rs38** [uholeschak/ediabaslib#60]
pretty old  and slow GT P 5110
https://en.wikipedia.org/wiki/Samsung_Galaxy_Tab_2_10.1
latest Deep OBD
connected with gender changer to FTDI USB cable 
Android 5.1.1 custom (https://slimroms.org/) witch is probably rooted and has extended debug settings.

Deep OBD starts and extracts fine, but whether I use the config generator or ediabas tool and choose USB/FTDI it does simply nothing. No warning / error. I am also unable to create trace files or similar. So hard to provide better info for this...

How could I check whether it can talk to the FTDI at all?

**Comment by uholeschak** [comment]
Do you get a popup regarding USB connection usage from the app? If not the tablet is probably not usable.

**Comment by uholeschak** [comment]
Please test the cable with an up to date Android device. If this is working correctly, your tablet is simply to old and you have to replace it or use a different Android.

**Comment by rs38** [comment]
you mean a pop up at app startup like "do you want to use the USB with this app"?
No there isn't. Wouldn't it be meaningful to have a error message, if DeapOBD cannot find or reach an USB device?

**Comment by uholeschak** [comment]
Yes if there is no popup USB is not available. I think this info is enough.

**Comment by Crabolog** [comment]
Am I correct that initial flashing via pickit and powering by 16&4 pins
should make the adapter visible as a bluetooth device without inserting it
into obd?

чт, 27 февр. 2020 г. в 13:13, Ulrich Holeschak <notifications@github.com>:

**Comment by uholeschak** [comment]
Bluetooth is independent of the PIC, must be visible always.

**Comment by Crabolog** [comment]
Got an adapter with BK3231 and bluetooth visible only while inserted into
obd

пн, 2 мар. 2020 г. в 18:15, Ulrich Holeschak <notifications@github.com>:

**Comment by uholeschak** [comment]
Without power supply it is of course not visible.

**Comment by Crabolog** [comment]
Nah, powered at home with 12v, not visible

пн, 2 мар. 2020 г. в 18:18, Ulrich Holeschak <notifications@github.com>:

**Comment by Crabolog** [comment]
However its reading and flashing

пн, 2 мар. 2020 г. в 18:21, Oleg Crabolog <crabeg23@gmail.com>:

**Comment by uholeschak** [comment]
Sorry I can't help you there, your hardware is unknown to me.

**Comment by rs38** [comment]
> pretty old and slow GT P 5110
> https://en.wikipedia.org/wiki/Samsung_Galaxy_Tab_2_10.1
> latest Deep OBD
> connected with gender changer to FTDI USB cable
> Deep OBD starts and extracts fine, but whether I use the config generator or ediabas tool and choose USB/FTDI it does simply nothing. No warning / error. I am also unable to create trace files or similar. So hard to provide better info for this...

wanted to add that the reason was the gender changer is not triggering the USB cable to be the slave. So when connecting a true OTG Cable, it works and the pop up is displayed.
Nevertheless it would be kind of helpful to have a check whether the USB connection is working at all or not.

**Comment by uholeschak** [comment]
If there is no USB popup the adapter is not detected. Use a newer tablet.

**Comment by rs38** [comment]
obviously you didn't get my message: tablet is fine, but attaching a USB OBD2 cable with a gender changer is not working. OTG is required and works fine. OTG defines / reverses master and slave in the USB connection. USB storage was also not possible. may be a beginner's mistake.

**Comment by uholeschak** [comment]
Sorry I don't not understand it. It is working now?

**Comment by rs38** [comment]
liegt's an der Sprache??? ja, es läuft jetzt mit einem OTG Kabel. nur mit einem weiblich-weiblich Adapter weiß das Tablet nicht, dass es nun mit einem FTDI als slave reden soll. Das war ne Fehlbedienung, die offenbar nicht jedem klar ist.

**Comment by uholeschak** [comment]
Prima, dann ist ja alles ok, das kann schon sein, dass es an der Sprache liegt.
Ja dafür sind die OTG Kabel ja auch da.
