### ISSUE TITLE
binaries and elm version

### ISSUE THREAD

**Issue by aster94** [uholeschak/ediabaslib#62]
Hello,

I found this repo while i was searching for new firmwares for the elm327, actually i don't have a bmw.
may i ask you from which version of the elm327 did you started for your improvements? and from where did you found it?
thanks

**Comment by uholeschak** [comment]
I expect this chapter answers your question:
https://github.com/uholeschak/ediabaslib/blob/master/docs/Replacement_firmware_for_ELM327.md#elm327-v15-firmware

**Comment by aster94** [comment]
looks like you wrote your firmware without using a 1.x version from the elm327
my compliments!

**Comment by uholeschak** [comment]
Yes the replacement firmware has nothing to do with ELM327 and is not ELM compatible.
