### ISSUE TITLE
Detect if D-CAN cable has your firmware?

### ISSUE THREAD

**Issue by terraphantm** [uholeschak/ediabaslib#64]
Sorry if this isn't the appropriate place to ask this. But basically I'm working on an  flashing application for the MSS6x series DMEs. It works very well with EdiabasLib along with a D-CAN cable flashed with your firmware. On a standard cable, a brick is all but guaranteed.

Is there a way to detect if a D-CAN cable is flashed with your firmware? That would make me a lot more comfortable about releasing since I'm sure there's someone who won't listen to my warnings.

**Comment by uholeschak** [comment]
If you check the source code, the fimrware responses to some internal commands (I don't remember any more), perhaps you could use one of them for testing.
