### ISSUE TITLE
Execution errors when running certain jobs with Ediabaslib.dll & Ediabaslib Api32.dll

### ISSUE THREAD

**Issue by Martyn-Dev** [uholeschak/ediabaslib#65]
Hi,

I have been using Ediabaslib.dll successfully in a number of my projects, however I believe I may have stumbled upon a bug. I can successfully execute the job in question using identical parameters using Tool32 and the stock api32.dll, however when I execute the job with the ediabaslib api32.dll I get an error. The same error occurs if I repeat the test using EdibasTest.exe too.

I am running the job "FLASH_LOESCHEN" from the SMG2.prg file and passing the parameter "010100000000000000FF0000006000600010200300FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF03".

The errors I receive are "DATATRANSMISSION TO INTERFACE DISTURBED" or "ERROR_ECU_PARAMETER".

Attached are trace logs from the working api32.dll and tool32, along with the traces from the non working ediabaslib api32.dll.
[ediabaslib_logs.zip](https://github.com/uholeschak/ediabaslib/files/4538792/ediabaslib_logs.zip)

Many thanks,

Martyn

**Comment by uholeschak** [comment]
Thanks for the info, do I need the ECU for testing?

**Comment by Martyn-Dev** [comment]
Unfortunately yes. 'FLASH_LOESCHEN' is a destructive process as it will erase the flash, however I have a bench setup for testing. I can arrange a remote session or something perhaps?

**Comment by uholeschak** [comment]
Perhaps if I have the ECU response telegrams I could try to simulate it.

**Comment by Martyn-Dev** [comment]
I can set the logging to the highest and execute the working process in WinKFP if you wish?

**Comment by uholeschak** [comment]
Thanks at least you could try

**Comment by Martyn-Dev** [comment]
API trace level 8 / IFH trace level 3

[working_flash_winkfp.zip](https://github.com/uholeschak/ediabaslib/files/4538968/working_flash_winkfp.zip)

**Comment by uholeschak** [comment]
Thanks I will check this when I have some time, maybe in one or two weeks.

**Comment by Martyn-Dev** [comment]
Thanks, if there is anything you want me to try in the meantime, please let me know.

**Comment by Martyn-Dev** [comment]
Donation sent too :)

**Comment by uholeschak** [comment]
Thanks very much, I will try to check it as soon possible, but at the moment are also other problems.

**Comment by terraphantm** [comment]
Hello, I can confirm that this same issue also occurs with 10MSS54.prg; I suspect the same will hold true for other DS2 modules.

**Comment by uholeschak** [comment]
Up to now I had no time to check this.
Which adapter have you used?

**Comment by Martyn-Dev** [comment]
I am using a K/DCAN cable flashed with your firmware.

**Comment by uholeschak** [comment]
This firmware at least is not supporting telegrams longer than 255 bytes.

**Comment by Martyn-Dev** [comment]
I'm not sure that matters as I'm using the same firmware/cable with both your libraries and with plain Ediabas.

**Comment by uholeschak** [comment]
When I finally have some time I will check it, but there are more urgent problems a the moment.

**Comment by uholeschak** [comment]
I have check the logs now, it seems that the ECU rejects the erase request for some reasons, the transmission error is only a secondary failure. The problem is, that seed_key generates variables telegrams.
Could you create some more log files with EdiabasLib and standard EDIABAS so I could see how the key modifies the telegrams?

**Comment by Martyn-Dev** [comment]
Sure thing!

**Comment by Martyn-Dev** [comment]
So that's a quick tool32 log containing a 'blocklaenge_max', followed by a 'seed_key', followed by a 'flash_schreiben_ende' with data '010100000000000000FF0000006000600010200300FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF03' and then a 'flash_loeschen' with the same data (data box ticked).

[ifh.trc.working.txt](https://github.com/uholeschak/ediabaslib/files/4622070/ifh.trc.working.txt)

Will get some more logs in a moment.

**Comment by uholeschak** [comment]
Thanks, I will check them later.

**Comment by Martyn-Dev** [comment]
[api.trc.ediabaslib.api32.log.txt](https://github.com/uholeschak/ediabaslib/files/4622112/api.trc.ediabaslib.api32.log.txt)
[ifh.trc.ediabaslib.api32.log.txt](https://github.com/uholeschak/ediabaslib/files/4622113/ifh.trc.ediabaslib.api32.log.txt)

Logs from using your api32.dll

**Comment by uholeschak** [comment]
Could you also add the API trace for ifh.trc.working?

**Comment by Martyn-Dev** [comment]
Sorry to be ignorant, but how do i enable API tracing for Tool32 for standard Ediabas?

**Comment by uholeschak** [comment]
In working_flash_winkfp.zip you enabled the logging:
API trace level 8 / IFH trace level 3

**Comment by Martyn-Dev** [comment]
That was using WinKFP, Tool32 doesnt have the option to enable API tracing.

**Comment by uholeschak** [comment]
Could you configure it directly in ediabas.ini?

**Comment by Martyn-Dev** [comment]
[api.trc.working.txt](https://github.com/uholeschak/ediabaslib/files/4622264/api.trc.working.txt)

Here you go, it just needed 

ApiTrace = 3

Bunging in ediabas.ini

**Comment by uholeschak** [comment]
Thanks, and is this file matching the contents of the old ifh.trc.working.txt?

**Comment by Martyn-Dev** [comment]
Yes, same process, same parameters but a different session. I can send you a syncronised log (from same session) if this one is no good.

**Comment by uholeschak** [comment]
Please send one from the same session.

**Comment by Martyn-Dev** [comment]
Same session.

[ifh.trc.txt](https://github.com/uholeschak/ediabaslib/files/4622289/ifh.trc.txt)
[api.trc.txt](https://github.com/uholeschak/ediabaslib/files/4622290/api.trc.txt)

**Comment by uholeschak** [comment]
I think that I have found the reason, the .prg files configures a timeout of 0 while flashing and EDIABAS uses 60 sec. in this case. Are all flashing problems you have related to the DS2 protocol?

**Comment by Martyn-Dev** [comment]
I believe so buddy.

**Comment by uholeschak** [comment]
Could you check this? I am not sure if I have to modify it also for more protocols.

**Comment by Martyn-Dev** [comment]
I experience the same issue when doing the same process on the MSS54 which uses the same DS2 protocol.

**Comment by uholeschak** [comment]
Are you able to check if this issue is only related to DS2 protocol and not e.g. BWM-FAST?

**Comment by Martyn-Dev** [comment]
I believe it holds true for anything pre KWP2000. @terraphantm may be able to confirm as I believe he is using EdiabasLib successfully with BMW-FAST.

**Comment by uholeschak** [comment]
My problem is simply that I am not sure if I could generally set the timeout to 60 sec. if the value is 0.

**Comment by uholeschak** [comment]
I have attached a new api32.dll could you check if this fixes the issue?
[Api32.zip](https://github.com/uholeschak/ediabaslib/files/4634530/Api32.zip)

**Comment by Martyn-Dev** [comment]
That appears to have worked fine using the updated api32.dll thanks!

**Comment by Martyn-Dev** [comment]
WinKFP flash worked fine.

**Comment by uholeschak** [comment]
Thanks for the info, at the moment I have modified it only for DS1 and DS2. It would be interesting if other protocols are also involved.

**Comment by uholeschak** [comment]
I have added the new timeout handling now also for concept 1 to DS2. I think I will close this ticket now and if you experience problems with other protocols you could reopen it.

**Comment by Martyn-Dev** [comment]
Awesome, thank you very much for fixing.
