### ISSUE TITLE
Documention unclear: Custom Bluetooth firmware 

### ISSUE THREAD

**Issue by LeisureLadi** [uholeschak/ediabaslib#67]
Dear all,

first of all thanks for all the efforts you put in to this really exciting project. I was able to follow all the steps to modify ELM327 adapters up to the point when I wanted to change the bluetooth adapter with the mostly used BK3231 chip to a board with BC04 chip.

The doc "Custom Bluetooth firmware" says: **"For HC-04, HC-05, HC-06 Bluetooth adapters which are built on CSR BC03 and BC04 (BlueCore 3/4) chipsets, there is a custom firmware available."**

Sorry for my ignorance if I missed the relevant section in the docs, but I couldn't find any hint about which firmware is meant. Is it the firmware saved in the master file in **"\ediabaslib-master\EdiabasLib\CanAdapterElm\CanAdapterElm.X\Firmware\hc04"** or is it one of the firmwares saved in **"\ediabaslib-master\EdiabasLib\CanAdapterElm\CanAdapterElm.X\Firmware\spp_uart"**?

Second question I have is: in the master zip file there is the earlier mentioned directory "\ediabaslib-master\EdiabasLib\CanAdapterElm\CanAdapterElm.X\Firmware\**hc04**" and another "\ediabaslib-master\EdiabasLib\CanAdapterElm\CanAdapterElm.X\Firmware\**hc06**" which is not mentioned in the documentation. Is there a significant difference between them? The only difference described in the internet is, that HC04 is industrial grade and HC06 is consumer grade.

Third question is: there seem to be firmware files included for the BK3231 chips as well in **"\ediabaslib-master\EdiabasLib\CanAdapterElm\Other"**. Does this firmware provide any benefit over the pre-installed firmware coming with the BK3231 module? In case it does, which PIC18 firmware version needs to be installed with this BK3231 firmware?

Would be nice if someone could help me with this.

Best regards,
Ladi

**Comment by uholeschak** [comment]
1) It's the firmware in the current release package https://github.com/uholeschak/ediabaslib/releases
2) The adapter firmware you use has to match the firmware in the Bluetooth chip.
3) "Other" was only for some internal tests and should be ignored.
