### ISSUE TITLE
Yandex Translations Are Gone

### ISSUE THREAD

**Issue by SyvelDesign** [uholeschak/ediabaslib#69]
Hi, I just installed DeepOBD today and when I tried to get an API ket for Yandex Translations it says that Yandex doesn't offer free API's anymore. Is there another solution? How do I go about getting a paid API if it's not too expensive?

**Comment by uholeschak** [comment]
This is bad but I can't change that, if course you cold pay for it:
https://translate.yandex.com/developers/offer/prices

**Comment by uholeschak** [comment]
Maybe this is an alternative:
https://mymemory.translated.net/doc/usagelimits.php

**Comment by uholeschak** [comment]
I think the IBM translator is a good solution:
https://cloud.ibm.com/docs/language-translator?topic=language-translator-about

**Comment by uholeschak** [comment]
In the beta:
https://play.google.com/apps/testing/de.holeschak.bmw_deep_obd
IBM Watson is integrated.

**Comment by uholeschak** [comment]
Released
