### ISSUE TITLE
ECUs are missing since the last Deep OBD updates in BMW i3/i8 

### ISSUE THREAD

**Issue by rs38** [uholeschak/ediabaslib#73]
e.g. the SME Ecu.
It doesn't show up anymore in the config generator.
I can connect to it with the SME group file but then all the nice values retrieved from "the database" are missing.
Any idea?

**Comment by uholeschak** [comment]
Basically the ECU should response to the broadcast command, without more details this is impossible to answer. Please check the trace file.

**Comment by rs38** [comment]
I sent the trace file to you via the in-app function. How can you identify the mail?

**Comment by uholeschak** [comment]
You have to specify the app id or you have to write a special comment while sending.

**Comment by rs38** [comment]
Deep OBD für BMW und VAG
Version: 1.2.256
Id: 4f731353-4de6-442d-91fd-2c625cc7ae69

**Comment by uholeschak** [comment]
Sorry there is no trace with this ID. Please specify you email address while sending or add a special comment I could search for.

**Comment by rs38** [comment]
I retestet and resend a trace from that device.
It turns out that the global settings checkboxes for "broadcast" and "BWM database" are cleared with every app start. 
Are they supposed not to be saved anymore?

**Comment by uholeschak** [comment]
This is a bug, I will check it.

**Comment by rs38** [comment]
the same here. it occurs only ~2 of 5 times...

**Comment by uholeschak** [comment]
What exactly are you doing to produce the problem?

**Comment by rs38** [comment]
I left the car with the settings check boxes enabled and if I now check the app (unplugged) it's unchecked.
There are 2 git commits that touched the settings stuff in the last 6 weeks. It must be there, because it was working fine before.

**Comment by rs38** [comment]
> Deep OBD für BMW und VAG
> Version: 1.2.256
> Id: 4f731353-4de6-442d-91fd-2c625cc7ae69

yes 1.2.256 and the problem was already in the version before (but that was probably a beta)

**Comment by uholeschak** [comment]
Was it only lost in version 1.2.255? This could be possible.

**Comment by rs38** [comment]
no, the bug is in the current version.

**Comment by uholeschak** [comment]
Could you create a video who to reproduce it?

**Comment by rs38** [comment]
I think it would be much easier to check 1.2.255 again if it works fine. How Do i get it?

pretty sure that
`if (!ActivityCommon.StaticDataInitialized || !_instanceData.GetSettingsCalled)`
is not working as supposed.

**Comment by uholeschak** [comment]
This is only the fix, but the problem must be older.

**Comment by uholeschak** [comment]
There is now a Beta Version:
https://play.google.com/apps/testing/de.holeschak.bmw_deep_obd
Could you check if this fixes the problem?

**Comment by rs38** [comment]
checked new beta 1.2.258:

1.	no cable attached
2.	starting DeepOBD App
3.	goto global settings
4.	make settings changes (broadcast+BMW database)
5.	go back to main menu
6.	check settings again, still checked fine.
7.	exit the App
8.	force the app to close by Android’s App settings
9.	go back to the app, check settings, they are still lost

**Comment by uholeschak** [comment]
Sorry I can't reproduce the problem. How did you stop the app? By the force stop button in the system menu?

**Comment by rs38** [comment]
yes, as explained via email

**Comment by uholeschak** [comment]
Could you create a video?

**Comment by rs38** [comment]
no, sorry. don't you believe me???
what could be misunderstood with steps 1.-9. ?

**Comment by uholeschak** [comment]
I simply can't reproduce it, it must a special condition or setting that is unknown.
Tried reinstalling the app?

**Comment by rs38** [comment]
yes, reinstall was my first try before opening the issue.
let me see if I find another Android device if it behaves differently.

Best bet would be to try an older version with loading an old .apk
can you provide?
I could only narrow down the versions since it occurs, it was in the last 4-6 weeks and according to the commits there were many changes with global settings.

**Comment by uholeschak** [comment]
The changes in the global settings are mostly after to problem occurred to fix it.
I expect that this is an indirect effect due to overflow of some memory or similar.

**Comment by rs38** [comment]
can you direct me to a trustworthy source of an ~3 month old version of deep OBD .akp?

**Comment by uholeschak** [comment]
https://www.dropbox.com/s/25wfq9seu0hb68b/298.apk?dl=0

**Comment by uholeschak** [comment]
Jetzt hat mir auch wieder Jemand geschrieben, das die Neuinstallation das Problem behebt.

**Comment by uholeschak** [comment]
I think that I have found now the reason for settings failure. A data type has changed that is now incompatible and causes an exception. This is why reinstalling fixes the problem, because all data will be deleted.
