### ISSUE TITLE
programming for Deep OBD

### ISSUE THREAD

**Issue by thijsdeschildre** [uholeschak/ediabaslib#75]
I succesfully programmed Binaries-20200517\CanAdapterElm\yc1021\CanAdapterElm.X.production.unified.hex to my adapter with the right PIC and matching bluetooth adapter. MPLab sees the PIC and says programming and verification are good. Bluetooth sees the device still show up as "OBDII" and Deep OBD says "adapter type detection failed".

Am I missing something? I somehow get the impression Deep OBD can program an adapter too, but I can't figure it out from the documentation.

**Comment by uholeschak** [comment]
Maybe your PIC firmware type is not matching Bluetooth firmware type.

**Comment by thijsdeschildre** [comment]
I'm not sure I understand. My board has the yc1021 bluetooth adapter. So that bluetooth adapter can have different firmware versions, and not all of them all supported?
Should the device connect to Bluetooth as "Deep OBD" or something?

**Comment by uholeschak** [comment]
Did you change the yc1021 settings:
https://github.com/uholeschak/ediabaslib/blob/master/docs/Replace_Elm327_BT_Mini_Firmware.md#step1-program-the-yc1021-bt-settings
