### ISSUE TITLE
ResultData with Int64

### ISSUE THREAD

**Issue by RainbowXie** [uholeschak/ediabaslib#76]
Hi,

I am reading ApiInternal code, and find 
1. you convert ResultData.OpData to Int64 to Store, and convert back when using them.
2. I notice you use `resultData.OpData is long` rather than ResultType to get OpData type.

I don't know why are you do that. If could, pls tell me.

thanks.

**Comment by uholeschak** [comment]
What exactly do you mean? long is Int64.
