### ISSUE TITLE
Deep OBD won't connect

### ISSUE THREAD

**Issue by the-vty** [uholeschak/ediabaslib#77]
Hi,

Given:
1. BMW E46
2. Bluetooth ELM317 flashed with Binaries-20200517/CanAdapterElm/spp_uart/CanAdapterElm.X.production.unified.hex
and with BC417 flashed with custom bluetooth firmware.
After flashing I entered "82 F1 F1 FE FE 60" and got the proper response.
3. Pins 7 and 8 are connected.

When I start the Deep OBD android app it asks me to build configuration, i'm getting on the adapter configuration page, it reads the bluetooth configuration where I can change name, pin etc. It shows the battery voltage 12.6V, version 0.15/0.15, but no ignition status. When I finish with the suggested configuration actions the app doesn't connect (the button on left to the wrench keeps showing DISCONNECTED and stays grayed)

If I do "FLASH ELM327 FIRMWARE" on the bluetooth configuration page I'm able to use ELM327 apps, like ELM327 Identifier and Car Scanner. But if I start Deep OBD after that it shows the message that "it's recommended to update ELM327 firmware with the replacement software". I'm saying "YES" and do "FLASH REPLACEMENT FIRMWARE". After flashing it still stays grayed disconnected.

It suggests me that the bluetooth and electrical part of OBD are working correctly. I can flash both firmwares and save Bluetooth config.

Either I'm missing something or the replacement firmware doesn't work properly.

Please help me!
Thanks a lot!
victor

**Comment by uholeschak** [comment]
Everything seems to be ok, It sounds like that you have simply not generated a configuration with the generator.
