### ISSUE TITLE
Question: MHD Orange Support

### ISSUE THREAD

**Issue by wkronmiller** [uholeschak/ediabaslib#78]
Hey there, apologies in advance if you already have documentation on this that I missed. 

I have an N54 E90 BMW (2007 335xi) and an MHD Orange adapter for it: <https://mhdtuning.com/pages/mhd-wireless-adapter>. 

Does BMWDeepOBD support the MHD orange adapter out of the box or would I need to modify either the program or adapter in some way?

Thanks!

**Comment by uholeschak** [comment]
If it's am genuine ELM327 it should work.
