### ISSUE TITLE
ICOM Nano Support

### ISSUE THREAD

**Issue by viktormorozow** [uholeschak/ediabaslib#79]
Hallo, ich habe ein original ICOM Nano, dies kann ich mit DeepOBD zwar nutzen nach manueller Eingabe der IP (192.168.4.1), die App fragt aber immer wieder ob man nicht das WLAN/Netz wechseln will. Anscheinend wird das ICOM Nano nicht so richtig erkannt, funktioniert aber in der App soweit alles.

Kann man vielleicht den Support für ICOM Nano vervollständigen in DeepOBD/EdiabaLib?

Falls Informationen zum Interface benötigt werden, einfach melden. Für Tests stehe ich auch zur Verfügung.

lg

![2020-09-13 12_58_34-Window](https://user-images.githubusercontent.com/8280833/93641057-f32ad700-f9fb-11ea-8d48-9f88ede5ff09.png)

**Comment by uholeschak** [comment]
Ja das ist bekannt. Wenn Sie mir einen Adapter zusenden, kann ich das korrekt implementieren, sonst ist das zu aufwendig.

**Comment by viktormorozow** [comment]
Das ist schwierig mit Zusenden, nutze den selbst immer wieder. Es funktioniert ja soweit alles, vielleicht muss man ja nur die IP zu den bekannten Geräten hinzufügen?

**Comment by uholeschak** [comment]
Nein da ist mehr zu ändern.
Ok, dann scheint es nicht so wichtig zu sein.
