### ISSUE TITLE
BC-04 firmware

### ISSUE THREAD

**Issue by Vernerio** [uholeschak/ediabaslib#8]
Hi, First I have to say thanks from all of this...
But I have also problem with programming bc-04 to elm327.
Elm chip is the pic18f25k80 and BT BK3231, I use Pickit3.
With bc-04 firmware it was unworking state, no elm, no DeepOBD. But with Default unified firmware it worked right away and also received firmware update after that.
It's already superior with the DeepOBD/inpa/ista, I also made the k-line switch.
But what I doing wrong with the programming?
What I miss with this firmware, speed, stability, configurability?

Is there any way to use that with other PC software as a INPA adapter, like Siemens MS43 flash tool, Romrider logger, they need a standard Com port. If I pair that BT-device with Windows 10, I got two Bluetooth Com ports, PC&adapter side openable ports. But those ports not work with any other app what I have tried. Maybe they need FTDI driver?

**Comment by uholeschak** [comment]
If you use the BC-04 firmware you have to replace the Bluetooth chip with an BC-04 Bluetooth chip of course.
You could only use the adapter with EdiabasLib.
