### ISSUE TITLE
how to use code fragments

### ISSUE THREAD

**Issue by thijsdeschildre** [uholeschak/ediabaslib#82]
There are some templates to generate a configuration to show all logged errors in the fault memory, but how are these used?
Put them in a .ccfg? 
https://github.com/uholeschak/ediabaslib/blob/master/docs/Page_specification.md

**Comment by uholeschak** [comment]
Perhaps you should check the examples:
https://github.com/uholeschak/ediabaslib/tree/master/BmwDeepObd/Xml
