### ISSUE TITLE
IINPA Fehler bei Livedaten Erfassung

### ISSUE THREAD

**Issue by Alpha330i** [uholeschak/ediabaslib#86]
Ich bekommen nach einigen Minuten Livedaten Erfassung am E60 Bj 2005 plötzlich den Fehler Ifh 0003 Datenübetragung-Hostinterface gestört. 

Adapter: ein von mir selbst programmierter PIC18f25k80 und YC1021 BT Chip, der wiederum mit der modified.bin aus den Binarys geflasht wurde. Im Grunde funktioniert dieser ja auch, bis auf die instabile Kommunikation.

Hat jemand das Problem gehabt oder kennt einen Lösungweg?

![fehler](https://user-images.githubusercontent.com/75012658/100202344-7afff680-2f01-11eb-94e7-bd73bc3449f9.jpg)

**Comment by uholeschak** [comment]
Kann man unter Umständen in den Trace etwas erkennen? Es wird schon ein Problem mit der Verbindung bestehen ...

**Comment by Alpha330i** [comment]
Leider nicht, gibt es bekannte Probleme mit dem YC1021? 
Könnte der E60 2005 durch eine Pin 7+8 Brücke gestört werden in der Verbindung?

**Comment by uholeschak** [comment]
Die Brücke wird es eher nicht sein, Sie können ja mal mit einem anderen Bluetooth Chip testen ...
