### ISSUE TITLE
Sourcecode für den ESP8266EX

### ISSUE THREAD

**Issue by leschi** [uholeschak/ediabaslib#87]
Guten Tag,

wo ist der Sourcecode für den ESP8266EX zu finden?

Ich sehe nur die kompilierte sysdata.bin und userdata.bin

Vielen Dank.

**Comment by uholeschak** [comment]
Read this doc:
https://github.com/uholeschak/ediabaslib/blob/master/docs/Replace_Elm327_Wifi_Mini_Firmware.md
