### ISSUE TITLE
Programmed interface link in Replacement_firmware_for_ELM327.md leads to unavailable product

### ISSUE THREAD

**Issue by anarmanafov1** [uholeschak/ediabaslib#88]
The link https://www.ebay.de/itm/254785861413 leads to no product.

**Comment by anarmanafov1** [comment]
@uholeschak is there any intent on listing the item? If not I can contribute by removing the part of the documentation regarding purchasing a pre-programmed interface.

**Comment by uholeschak** [comment]
Is this a joke? The are simply sold.
