### ISSUE TITLE
DIS on VMware through ifhsrv.exe (ifhsrv.exe throws can`t create file) using ADS interface through PL2303

### ISSUE THREAD

**Issue by str90** [uholeschak/ediabaslib#89]
I`m using tinyADS interface connected with ugreen`s RS232 to USB adapter (PL2303 chip). When I try to read DME on DIS virtual machine that uses ifhsrv.exe, ifhsrv.exe throws createFile error.

**Comment by uholeschak** [comment]
Why are us using ihfhsrv? EdiabasLib is an api32.dll replacement, probably your setup is incorrect.

**Comment by str90** [comment]
How i might use DIS then ?

**Comment by uholeschak** [comment]
Officially not supported. If you find a way it's ok  ...

**Comment by uholeschak** [comment]
Of cource nobody stops you to implement it and and send a patch ...
