### ISSUE TITLE
Update to latest zlib.managed.

### ISSUE THREAD

**Issue by AraHaan** [uholeschak/ediabaslib#91]
I also plan to make a version that comes with all of my packages as well too in the future, that would mean future updates would need to install ``Elskom.Sdk`` for the zlib stuff (don't worry the packages are basically like an metapackage with all of the dlls and stuff embedded inside and would only be consumed when there is actual code that uses the files inside like in the normal .NET Core SDK metapackages.

1.1.4 is the current stable of ``zlib.managed`` on nuget, the other package ``Elskom.Sdk`` will contain version 1.1.5.

**Comment by uholeschak** [comment]
At the moment I am still at an older version, I have not updated the project containing this for some time.
