### ISSUE TITLE
MPLAB X IDE & build issues of CanAdapterElm.X

### ISSUE THREAD

**Issue by XantheFIN** [uholeschak/ediabaslib#92]
It seems be not working at all. Tried now with on Windows 10 and macOS.

What is versions this has been build on?

There is red text after opening project and going Project Attributes -> Please select compiler version

XC8 V2.31 i do select then for default

C standard?
What is Linker options?
C99 or, C90 or install older which has C89? (this comes from somewhere from configs)

If i try get hex out of that project i get error at Export... 
"The current license does not permit the selected optimization level".. etc junk

Then finally it stops at error

"nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed"

**Comment by uholeschak** [comment]
You have install XC8 1.33 in pro mode, see main.c:
`#if _HTC_EDITION_ != 2`
`#error Compiler is not PRO mode, generated code will be too slow`
`#endif`
`#if __XC8_VERSION != 1330`
`#error Timing is optimized for XC8 1.33`
`#endif`
