### ISSUE TITLE
[REQUEST] Ability to add actuator functions to a page

### ISSUE THREAD

**Issue by NotDonaldTrump** [uholeschak/ediabaslib#93]
Hello!

I own a 2003 R50 Mini Cooper and I’m absolutely loving Deep OBD. 

Would like to ask if we’re were possible to add the ability to add “actuator function” buttons to a page, a good example for my car would be through the BCM, using it to open the hatch just my pressing a button available to me instead of unlocking car etc. 

Would just be great overall. 

Unsure if this can currently be accomplished but any help/addition if this feature would be amazing

**Comment by uholeschak** [comment]
At least this is not so easy, maybe in one year or two?
