### ISSUE TITLE
KW1281 protocol and Skoda felicia

### ISSUE THREAD

**Issue by damiano94** [uholeschak/ediabaslib#94]
Hi
Will this Replacement firmware for ELM327 work with Skoda felicia ? It uses KW1281 protocol described here https://www.blafusel.de/obd/obd2_kw1281.html For now i'm using vag kkl cable and vcds lite but I want to use bluetooth adapter and android app (deep obd).

**Comment by uholeschak** [comment]
Perhaps you simply have to try ...
