### ISSUE TITLE
KW902 with PIC18F25K80 and BK3231S

### ISSUE THREAD

**Issue by HeadCrash66** [uholeschak/ediabaslib#97]
Hi,

I bought the following adapter and wanted to flash the alternative firmware.
The flashing into the PIC18F25K80 worked but there seems to be problems with the Bluetooth IC BK3231S.

I liked the adapter because of the shape, if someone has similar plans may take this as warning.
Or if someone has an idea how to get it to work anyway I would be happy.

Best regards.

**Comment by uholeschak** [comment]
If you use the default firmware you have the reduced baud rate but no problem.

**Comment by Alpha330i** [comment]
Ich habe mich vor kurzem an einem BC417 Chip probiert und festgestellt, dass mein bestellter Chip nur 6mb flash size hat. Nun erhalte ich die Nachricht beim flashen, dass das Image verkleinert wird, allerdings funktioniert das ganze dann nicht mit der spp_uart hex Datei auf dem PIC18. Die Kompakte Version funktioniert auch nicht. Gibt es dazu einen Workaround oder muss ich einen neues HC-05 Board kaufen in der Hoffnung ein besseren Chip zu erhalten?

**Comment by uholeschak** [comment]
You have to specify compact firmware:
![grafik](https://user-images.githubusercontent.com/7830051/114302593-f8e82700-9ac9-11eb-88e5-8f9082f0b6c3.png)

**Comment by Alpha330i** [comment]
which software are you using? maybe that could be a solution. 
There where compact files in your binaries with 4,4mb flash size but they didn't worked

And with the 6,2mb files im getting this message:
![blueflash](https://user-images.githubusercontent.com/75012658/114304510-d8bd6580-9ad3-11eb-84de-2c86cda3dc77.png)

**Comment by uholeschak** [comment]
You have to use BlueLab 4.1

**Comment by Alpha330i** [comment]
Is there an official download of BlueLab 4.1?  i don't find serious downloads

**Comment by uholeschak** [comment]
No the the product is not existing any more.

**Comment by HeadCrash66** [comment]
> 
> 
> If you use the default firmware you have the reduced baud rate but no problem.

Many thanks for your reply.
Unfortunately, the default firmware does not work. DeepODB can not access my Konnwei KW902.
With windows I can see two serial ports, so BT is still working, but none of them sends any reply.
I have checked the flash process with verify so I'm pretty sure that it was successful.

**Comment by uholeschak** [comment]
Maybe you have to analyze the traffic with an oscilloscope. Wrong baud rate?

**Comment by Alpha330i** [comment]
Thank you for your help, now it worked with a pullup resistor on tx line.

**Comment by uholeschak** [comment]
Yes for the compact firmware the pullup is required!

**Comment by Alpha330i** [comment]
Now the app recognizes that the adapter is connected (changing the Bluetooth name works), but as soon as I connect to the vehicle, no data is displayed, despite the correct config file. I also sent the trace file from "bensaf@outlook.de"

**Comment by uholeschak** [comment]
Have used the configuration generator?

**Comment by Alpha330i** [comment]
yes i used the configuration generator, but it wasn't able to read out the car (2004 E46). With other OBD Adapter which was bought from you, all is working fine. So i guess its something with the BT chip? ive attached some photos of the Adapter and what is shown on the app. The Hex File is also working fine as you can see on the first picture
![Screenshot_20210411-204718](https://user-images.githubusercontent.com/75012658/114317206-49ca4080-9b07-11eb-83ba-c257679ced97.png)
![adap](https://user-images.githubusercontent.com/75012658/114317229-5f3f6a80-9b07-11eb-8607-f724e413c1ab.jpg)

**Comment by uholeschak** [comment]
I expect you have to find the reason yourself ...

**Comment by Alpha330i** [comment]
Hmm i think those "fake" BC417 are not working correct, but anyway, i will try another one

**Comment by uholeschak** [comment]
Use an oscilloscope an analyze it ...
