### ISSUE TITLE
[DeepOBD] STN1170 OBDLink MX Bluetooth

### ISSUE THREAD

**Issue by david-bla** [uholeschak/ediabaslib#98]
Moin,

I am using a ODBLink MX Bluetooth adapter and used DeepOBD with it before (~some years ago).
Today I got some time off, alone with my car :stuck_out_tongue_winking_eye:  (e87 2009 123d) and downloaded DeepOBD on my current smartphone. But I was not able to generate a configuration because DeepOBD was not able to detect the adapter.

The Chip _(STN1170)_ claims to be __Fully compatible with the ELM327 AT command set__ and __Based on a
16-bit processor core, the STN1170 offers more features and better performance than any other ELM327 compatible IC.__

Some time ago, I changed the `firmware ID string` to some of the ELM ones, but I think this was reset. Maybe this was enabling it to work with DeepOBD _(this is just an idea and may be not the case)_.

I like to ask you for your opinion on these questions.
- Should it work? _(I will debug it myself)_
- Or do it required to change the firmware?
- Do you recommend a different adapter? _(I have some USB Wired ones and maybe they work over USB OTG)_
- What adapter or direct connection _(chip?)_ would you recommend for a performant and permanent connection to an onboard android system?

---

vielen dank für deine arbeit in diesem großartigen projekt!

**Comment by uholeschak** [comment]
Basically only original ELM327 chips will work and no clones. They are not "compatible".
